apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    app.kubernetes.io/component: {{ .Values.serviceName }}
