apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ int .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ .Values.serviceName }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.serviceName }}
          image: {{ .Values.image }}
          livenessProbe:
            httpGet:
              path: {{ .Values.urlPrefix }}/healthcheck
              port: {{ .Values.servicePort }}
            initialDelaySeconds: 40
          readinessProbe:
            httpGet:
              path: {{ .Values.urlPrefix }}/healthcheck
              port: {{ .Values.servicePort }}
            initialDelaySeconds: 40
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            # AGATE CONFIGURATION
            - name: ARLAS_URL_SEARCH
              value: {{ .Values.arlasSearchUrl | quote }}
            - name: AGATE_URL_HEADER
              value: x-forwarded-uri
            - name: AGATE_METHOD_HEADER
              value: x-forwarded-method
            - name: AGATE_JWT_HEADER
              value: authorization

            # ENDPOINT CONFIGURATION              
            - name: AGATE_CORS_HEADERS
              value: {{ .Values.cors.allowedHeaders | quote }}
            - name: AGATE_CORS_METHODS
              value: {{ .Values.cors.allowedMethods | quote }}
            - name: AGATE_CORS_ORIGINS
              value: {{ .Values.cors.allowedOrigins | squote }}
            - name: AGATE_HOST
              value: {{ .Values.cors.allowedHosts | squote }}

            - name: AGATE_PORT
              value: {{ .Values.servicePort | squote }}
            - name: AGATE_PREFIX
              value: {{ .Values.urlPrefix }}

            # LOGGING
            - name: AGATE_LOGGER_LEVEL
              value: {{ .Values.logger.loggingLevel }}
          volumeMounts:
            - name: agate-files
              mountPath: /app/conf/
              readOnly: true
      volumes:
        - name: agate-files
          configMap:
            name: agate-files-configmap

      # NODE SELECTION      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
