FROM gisaia/arlas-initializer

ADD content/data content/elasticsearch_mapping.json content/logstash_configuration content/server_collection.json content/WUI_configuration.json content/WUI_map_configuration.json /initialization/

ADD content/start.bash /

CMD /start.bash
