FROM gisaia/arlas-initializer

ADD content/logstash_configuration content/elasticsearch_mapping.json content/data content/WUI_configuration.json content/WUI_map_configuration.json /initialization/

ADD content/start.bash /

CMD /start.bash
