apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.permissions.serviceName }}
  labels:
    {{- include "arlasServices.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.services.permissions.serviceName }}
spec:
  replicas: {{ int .Values.services.permissions.replicaCount }}
  selector:
    matchLabels:
      {{- include "arlasServices.labels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.services.permissions.serviceName }}
  template:
    metadata:
      labels:
        {{- include "arlasServices.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.services.permissions.serviceName }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.services.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.services.permissions.serviceName }}
          image: {{ .Values.services.permissions.image }}
          securityContext:
            {{- toYaml .Values.services.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.services.permissions.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.services.servicePort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /admin/healthcheck
              port: http
            initialDelaySeconds: 40            
          readinessProbe:
            httpGet:
              path: /admin/healthcheck
              port: http
            initialDelaySeconds: 40
          env:
            # ENDPOINT CONFIGURATION
            - name: ARLAS_PERMISSIONS_APP_PATH
              value: /
            - name: ARLAS_PERMISSIONS_PREFIX
              value: {{ .Values.services.permissions.urlPrefix | quote }}
            - name: ARLAS_PERMISSIONS_BASE_URI
              value: "https://{{ .Values.dnsDomain }}{{ .Values.services.permissions.urlPrefix }}/"
            - name: ARLAS_PERMISSIONS_PORT
              value: {{ .Values.services.servicePort  | quote }}

            # ARLAS AUTH PUBLIC URIS
            - name: ARLAS_AUTH_PUBLIC_URIS
              value: {{ .Values.services.permissions.publicUris  | quote }}

            {{- include "arlasServices.corsEnv" . | nindent 12 }}
            {{- include "arlasServices.keycloakEnv" . | nindent 12 }}
            {{- include "arlasServices.cacheEnv" . | nindent 12 }}
            {{- include "arlasServices.loggingEnv" . | nindent 12 }}
            {{- include "arlasServices.elasticEnv" . | nindent 12 }}
            {{- if .Values.services.permissions.otel }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.services.permissions.serviceName }}
            {{- include "arlasServices.otel" . | nindent 12 }}
              # JVM CONFIG
            - name: JDK_JAVA_OPTIONS
              value: "-Xmx{{ .Values.services.permissions.jvmXmx }} -XX:+ExitOnOutOfMemoryError {{ .Values.services.server.trustStoreOptions }} -javaagent:/opt/app/opentelemetry-javaagent.jar"
            {{- else }}
            # JVM CONFIG
            - name: JDK_JAVA_OPTIONS
              value: "-Xmx{{ .Values.services.permissions.jvmXmx }} -XX:+ExitOnOutOfMemoryError {{ .Values.services.server.trustStoreOptions }}"
            {{- end }}
            {{- with .Values.services.permissions.extraEnv }}
            {{ toYaml . | nindent 12 }}
            {{- end }}

          volumeMounts:
          {{- include "arlasServices.mountCertificate" . }}
      volumes:
        {{- include "arlasServices.volumeCertificate" . }}

      # NODE SELECTION      
      {{- with .Values.services.permissions.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.permissions.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.permissions.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
