USER_ADMIN = "tech@gisaia.com"
ORG_1 = "org1.com"
USER_1_ORG_1 = "user1@" + ORG_1
USER_2_ORG_1 = "user2@" + ORG_1

ORG_2 = "org2.com"
USER_1_ORG_2 = "user2@" + ORG_2
USER_2_ORG_2 = "user2@" + ORG_2

ORPHAN = "orphan@org.com"
ORPHAN2 = "orphan2@org.com"

COLLECTION1_ORG_1_PRIVATE = 


INDEX = "courses"
USERS = [USER_1_ORG_1]
ES_ENDPOINT = "http://localhost:9200"

SQL_INIT = """
DELETE FROM APIKEY;
DELETE FROM APIKEYROLE;
DELETE FROM ROLEPERMISSION;
DELETE FROM PERMISSION;
DELETE FROM REFRESHTOKEN;
DELETE FROM TOKENSECRET;
DELETE FROM USER_DATA;
DELETE FROM USER_DATA_READERS;
DELETE FROM USER_DATA_WRITERS;
DELETE FROM USERROLE where userrole.id_role in (select id from role where ID_ORGANISATION IS NOT NULL);
DELETE FROM ROLE WHERE ID_ORGANISATION IS NOT NULL;
DELETE FROM ORGANISATIONMEMBER;
DELETE FROM ORGANISATION;
DELETE FROM USERS WHERE email <> 'tech@gisaia.com';
"""
