apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "arlas-cloud.server.fullname" . }}
  labels:
    {{- include "arlas-cloud.server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "arlas-cloud.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "arlas-cloud.server.selectorLabels" . | nindent 8 }}
      annotations:
        co.elastic.logs/enabled: "true"
    spec:
      serviceAccountName: {{ include "arlas-cloud.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: server
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          env:
            {{- if .Values.server.apm }}
            - name: JVM_OPTION
              value: "-javaagent:/opt/app/elastic-apm-agent.jar"
            - name: ELASTIC_APM_LOG_ECS_REFORMATTING
              value: "OVERRIDE"
            - name: ELASTIC_APM_LOG_ECS_FORMATTER_ALLOW_LIST
              value: "*"
            - name: ELASTIC_APM_SERVICE_NAME
              value: "arlas-server"
            - name: ELASTIC_APM_APPLICATION_PACKAGES
              value: "io.arlas"
            - name: ELASTIC_APM_USE_JAXRS_PATH_AS_TRANSACTION_NAME
              value: "true"
            - name: ELASTIC_APM_SECRET_TOKEN
              value: {{ .Values.elastic.apm.secret }}
            - name: ELASTIC_APM_SERVER_URLS
              value: {{ .Values.elastic.apm.url }}
            - name: ELASTIC_APM_ENVIRONMENT
              value: {{ .Values.dnsDomain }}
            - name: ELASTIC_APM_TRANSACTION_IGNORE_USER_AGENTS
              value: "GoogleHC/*, kube-probe/*, curl*, GoogleStackdriverMonitoring*"
            - name: JDK_JAVA_OPTIONS
              value: "-Xmx{{ .Values.server.jvmXmx }} -XX:+ExitOnOutOfMemoryError -javaagent:/opt/app/elastic-apm-agent.jar"
            {{- else }}
            - name: JDK_JAVA_OPTIONS
              value: "-Xmx{{ .Values.server.jvmXmx }} -XX:+ExitOnOutOfMemoryError"
            {{- end }}
            - name: ARLAS_CLOUD_SERVER_DNS
              value: {{ include "arlas-cloud.fullname" . }}-full-cache.{{ .Values.workspace }}.svc.cluster.local
            - name: ARLAS_XMX
              value: {{ .Values.server.jvmXmx }}
            - name: ARLAS_LOGGING_LEVEL
              value: {{ .Values.server.logger.loggingLevel }}
            - name: ARLAS_LOGGING_CONSOLE_LEVEL
              value: {{ .Values.server.logger.loggingConsoleLevel }}
            - name: ARLAS_LOGGING_FILE_LEVEL
              value: "OFF"
            {{- if .Values.server.auth.enabled }}
            - name: ARLAS_AUTH_ENABLED
              value: "true"
            - name: ARLAS_AUTH_POLICY_CLASS
              value: {{ .Values.server.auth.policyClass }}
            - name: ARLAS_AUTH_PERMISSION_URL
              value: http://{{ include "arlas-cloud.iamServer.fullname" . }}.{{ .Values.workspace }}.svc.cluster.local:{{ .Values.iamServer.service.port }}{{ .Values.iamServer.urlPrefix }}{{ .Values.server.auth.permissionUrl }}
            - name: ARLAS_AUTH_PUBLIC_URIS
              value: {{ .Values.server.auth.publicUris }}
            - name: ARLAS_AUTH_CERT_URL
              value: {{ .Values.server.auth.certUrl }}
            - name: ARLAS_AUTH_KEYCLOAK_URL
              value: {{ .Values.server.auth.keycloakUrl }}
            - name: ARLAS_AUTH_KEYCLOAK_REALM
              value: {{ .Values.server.auth.keycloakRealm }}
            - name: ARLAS_AUTH_KEYCLOAK_RESOURCE
              value: {{ .Values.server.auth.keycloakResource }}
            - name: ARLAS_AUTH_KEYCLOAK_SECRET
              value: {{ .Values.server.auth.clientSecret }}
            {{- end }}
            - name: ARLAS_CACHE_FACTORY_CLASS
              value: {{ .Values.server.cacheFactoryClass | quote }}
            - name: ARLAS_CACHE_TIMEOUT
              value: {{ .Values.server.cacheTimeout | quote }}
            - name: ARLAS_SWAGGER_RESOURCE_PKG
              value: {{ .Values.server.swaggerResource | quote }}
            - name: ARLAS_CORS_ENABLED
              value: {{ .Values.cors.enabled | quote }}
            - name: ARLAS_CORS_ALLOWED_ORIGINS
              value: {{ .Values.cors.allowedOrigins | squote }}
            - name: ARLAS_CORS_ALLOWED_HEADERS
              value: {{ .Values.cors.allowedHeaders | quote }}
            - name: ARLAS_CORS_ALLOWED_METHODS
              value: {{ .Values.cors.allowedMethods | quote }}
            - name: ARLAS_CORS_ALLOWED_CREDENTIALS
              value: {{ .Values.cors.allowedCredentials | quote }}
            - name: ARLAS_CORS_EXPOSED_HEADERS
              value: {{ .Values.cors.exposedHeaders | quote }}
            - name: ARLAS_PREFIX
              value: {{ .Values.server.urlPrefix }}
            - name: ARLAS_BASE_URI
              value: https://{{ .Values.dnsDomain }}{{ .Values.server.urlPrefix }}/
            - name: ARLAS_ADMIN_PATH
              value: {{ .Values.server.urlPrefix }}/admin
            - name: ARLAS_CUSTOM_JS
              value: {{ .Values.server.urlPrefix }}/swagger-static/custom-request-interceptor.js
            - name: ARLAS_ELASTIC_CREDENTIALS
              value: {{ .Values.elastic.credentials.explo | quote }}
            - name: ARLAS_ELASTIC_INDEX
              value: {{ .Values.server.elasticIndex }}
            - name: ARLAS_ELASTIC_NODES
              value: {{ .Values.elastic.nodes | join "," }}
            - name: ARLAS_ELASTIC_ENABLE_SSL
            {{- if .Values.elastic.ssl }}
              value: "true"
            {{- else }}
              value: "false"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.server.urlPrefix }}/admin/healthcheck
              port: http
            initialDelaySeconds: 40
          readinessProbe:
            httpGet:
              path: {{ .Values.server.urlPrefix }}/admin/healthcheck
              port: http
            initialDelaySeconds: 40
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}