version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    env_file: environment/elasticsearch
    ports:
      - $ARLAS_STACK_ELASTICSEARCH_HTTP_PORT:9200
      - $ARLAS_STACK_ELASTICSEARCH_TRANSPORT_PORT:9300
