version: "3"

networks:
  default:
    external:
      name: arlas

services:
  arlas-server:
    image: gisaia/arlas-server
    container_name: arlas-server
    environment:
      - "ARLAS_ELASTIC_CLUSTER=docker-cluster"
      - "ARLAS_ELASTIC_HOST=elasticsearch"
    ports:
      - 9999:9999
    command: ["/opt/app/wait-for-elasticsearch.sh", "elasticsearch", "9200"]
  arlas-wui:
    image: gisaia/arlas-wui
    container_name: arlas-wui
    ports:
      - 80:80
    volumes:
      - wui-configuration:/usr/share/nginx/html/

volumes:
  wui-configuration:
