version: '3'
services:

#################
# NGINX
#################
  nginx:
    image: gisaia/arlas-stack-nginx:${ARLAS_NGINX_VERSION:-latest}
    container_name: arlas-stack-nginx
    ports:
      - "81:81"
    networks:
      - arlas-net
    depends_on:
      - arlas-wui
      - arlas-builder
      - arlas-hub
      - arlas-server      
      - arlas-persistence-server
