version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster

      # To run elasticsearch in development mode, so that the user doesn't require to upgrade kernel setting `vm.max_map_count` on his machine. See the following documentation sections:
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode
      - discovery.type=single-node
      
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.graph.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
    ports:
      - 9200:9200 # TODO: make it configurable in `.env` file
      - 9300:9300 # TODO: make it configurable in `.env` file
