version: '3'
services:

#################
# ELASTIC
#################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:-latest}
    container_name: elasticsearch
    restart: always
    ulimits:
      memlock: {soft: -1, hard: -1}
      nofile:
        soft: 65536
        hard: 65536
    # Exposing port 9200 in order to be able to create indices and load data
    ports:
      - "9200:9200" # !EXPOSE!
    expose:
      - "9200"
    networks:
      - arlas-net
    volumes:
      - 'elasticsearch_data_node1:/usr/share/elasticsearch/data'
    healthcheck:
      test: "curl -s --user ${ELASTIC_USER}:${ELASTIC_PASSWORD} -X GET http://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'"
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      - discovery.type=single-node
      - cluster.name=arlas-es-cluster
      - node.name=arlas-data-node-1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
