services:

#################
# ARLAS PERMISSIONS
#################
  arlas-permissions-server:
    image: gisaia/arlas-permissions-server:${ARLAS_PERMISSIONS_VERSION:-latest}
    container_name: arlas-permissions-server
    restart: always
    expose:
      - "9996"
    networks:
      - arlas-net
    healthcheck:
      test: ["CMD","java","HttpHealthcheck.java","http://localhost:9996/admin/healthcheck"]
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      - ARLAS_PERMISSIONS_PORT=9996
      - ARLAS_PERMISSIONS_PREFIX=/arlas-permissions-server
      - ARLAS_PERMISSIONS_APP_PATH=/
      - ARLAS_AUTH_ENABLED=false
      - ARLAS_CACHE_TIMEOUT="${ARLAS_CACHE_TIMEOUT:-5}"
