version: "3"

networks:
  default:
    external:
      name: arlas

services:
  arlas-server:
    image: gisaia/arlas-server:6.6.0
    container_name: arlas-server
    env_file: environment/arlas-server
    ports:
      - $ARLAS_STACK_SERVER_PORT:9999
    command: ["/opt/app/wait-for-elasticsearch.sh", "$$ARLAS_ELASTIC_HOST", "$$ARLAS_ELASTIC_PORT"] # TODO: replace `elasticsearch` `9300` by 1st element of ARLAS_ELASTIC_NODES. Port is optional in ARLAS_ELASTIC_NODES, if none given, use 9200
  arlas-wui:
    image: gisaia/arlas-wui:6.0.1
    container_name: arlas-wui
    env_file: environment/arlas-wui
    ports:
      - $ARLAS_STACK_WUI_PORT:80
    volumes:
      - wui-configuration:/usr/share/nginx/html/

volumes:
  wui-configuration:
