version: '3'
services:
    arlas-wui:
        image: gisaia/arlas-wui:${ARLAS_WUI_VERSION:-23.0.0}
        container_name: arlas-wui
        environment:
            - ARLAS_USE_AUTHENT=false
            - ARLAS_PERSISTENCE_URL=${ARLAS_PERSISTENCE_URL:-http://localhost:81/persist}
            - ARLAS_HUB_URL=http://${LOCAL_HOST-localhost}:81/hub
            - ARLAS_WUI_BASE_HREF=/wui
        depends_on:
            - arlas-persistence-server
            - arlas-server
        ports:
            - 8096:80
        networks:
            - esnet
    arlas-hub:
        image: gisaia/arlas-wui-hub:${ARLAS_HUB_VERSION:-23.0.0}
        container_name: arlas-hub
        environment:
            - ARLAS_USE_AUTHENT=false
            - ARLAS_HUB_BASE_HREF=/hub
            - ARLAS_WUI_URL=http://${LOCAL_HOST-localhost}:81/wui
            - ARLAS_BUILDER_URL=http://${LOCAL_HOST-localhost}:81/builder
            - ARLAS_PERSISTENCE_URL=${ARLAS_PERSISTENCE_URL:-http://localhost:81/persist}
            - ARLAS_PERMISSIONS_URL=${ARLAS_PERMISSIONS_URL:-http://localhost:81/permissions}
        depends_on:
            - arlas-persistence-server
            - arlas-wui
            - arlas-builder
        ports:
            - 8094:80
        networks:
            - esnet
    arlas-builder:
        image: gisaia/arlas-wui-builder:${ARLAS_BUILDER_VERSION:-23.0.0}
        container_name: arlas-builder
        environment:
            - ARLAS_BUILDER_BASE_HREF=/builder
            - ARLAS_USE_AUTHENT=false
            - ARLAS_WUI_URL=http://${LOCAL_HOST-localhost}:81/wui
            - ARLAS_SERVER_URL=${ARLAS_SERVER_URL:-http://localhost:81/server}
            - ARLAS_PERSISTENCE_URL=${ARLAS_PERSISTENCE_URL:-http://localhost:81/persist}
            - ARLAS_PERMISSIONS_URL=${ARLAS_PERMISSIONS_URL:-http://localhost:81/permissions}
            - ARLAS_BASEMAPS=[
                {"name":"Basic","url":"https://api.maptiler.com/maps/basic/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://cloud.maptiler.com/static/img/maps/basic.png"},
                {"name":"Bright","url":"https://api.maptiler.com/maps/bright/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://cloud.maptiler.com/static/img/maps/bright.png"},
                {"name":"Outdoor","url":"https://api.maptiler.com/maps/outdoor/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://cloud.maptiler.com/static/img/maps/outdoor.png"},
                {"name":"Pastel","url":"https://api.maptiler.com/maps/pastel/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://cloud.maptiler.com/static/img/maps/pastel.png"},
                {"name":"Satellite Hybrid","url":"https://api.maptiler.com/maps/hybrid/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://cloud.maptiler.com/static/img/maps/hybrid.png"},
                {"name":"Streets","url":"https://api.maptiler.com/maps/streets/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://cloud.maptiler.com/static/img/maps/streets.png"},
                {"name":"Toner","url":"https://api.maptiler.com/maps/toner/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://cloud.maptiler.com/static/img/maps/toner.png"},
                {"name":"Topo","url":"https://api.maptiler.com/maps/topo/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://cloud.maptiler.com/static/img/maps/topo.png"},
                {"name":"Topographique","url":"https://api.maptiler.com/maps/topographique/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://cloud.maptiler.com/static/img/maps/topographique.png"},
                {"name":"Voyager","url":"https://api.maptiler.com/maps/voyager/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://cloud.maptiler.com/static/img/maps/voyager.png"},
                {"name":"Positron","url":"https://api.maptiler.com/maps/8bb9093c-9865-452b-8be4-7a397f552b49/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://api.maptiler.com/maps/8bb9093c-9865-452b-8be4-7a397f552b49/0/0/0.png?key=xIhbu1RwgdbxfZNmoXn4"},
                {"name":"Dark Topo","url":"https://api.maptiler.com/maps/99521f88-ff7f-4c7b-b1dc-05a5a773b1f1/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://api.maptiler.com/maps/99521f88-ff7f-4c7b-b1dc-05a5a773b1f1/0/0/0.png?key=xIhbu1RwgdbxfZNmoXn4"},
                {"name":"Streets-dark","url":"https://api.maptiler.com/maps/a1e62ee0-aca6-451a-a4b8-42250422a212/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://api.maptiler.com/maps/a1e62ee0-aca6-451a-a4b8-42250422a212/0/0/0.png?key=xIhbu1RwgdbxfZNmoXn4"},
                {"name":"Streets-light","url":"https://api.maptiler.com/maps/208a41eb-368f-4003-8e3c-2dba0d90b3cb/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://api.maptiler.com/maps/208a41eb-368f-4003-8e3c-2dba0d90b3cb/0/0/0.png?key=xIhbu1RwgdbxfZNmoXn4"}
                ]
        depends_on:
            - arlas-persistence-server
            - arlas-wui 
        ports:
            - 8095:80
        networks:
            - esnet
    arlas-persistence-server:
        image: gisaia/arlas-persistence-server:${ARLAS_PERSISTENCE_VERSION:-23.0.0}
        container_name: arlas-persistence-server
        environment:
            - ARLAS_PERSISTENCE_PORT=9997
            - ARLAS_PERSISTENCE_PREFIX=/arlas-persistence-server
            - ARLAS_PERSISTENCE_APP_PATH=/
            - ARLAS_AUTH_ENABLED=false
            - ARLAS_PERSISTENCE_ENGINE=file
            - ARLAS_PERSISTENCE_LOCAL_FOLDER="${ARLAS_PERSISTENCE_LOCAL_FOLDER:-/tmp/persist/}"
        expose:
            - "9997"
        ports:
            - 19997:9997
        volumes:
            - ${ARLAS_PERSISTENCE_LOCAL_FOLDER_HOST:-/tmp/persist/}:${ARLAS_PERSISTENCE_LOCAL_FOLDER:-/tmp/persist/}:rw
        networks:
            - esnet
    elasticsearch:
        image: 'docker.elastic.co/elasticsearch/elasticsearch:7.9.2'
        container_name: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - node.name=docker-node
            - cluster.initial_master_nodes=docker-node
            - cluster.routing.allocation.disk.threshold_enabled=false
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
        ulimits:
            memlock: {soft: -1, hard: -1}
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - 'esdata1:/usr/share/elasticsearch/data'
        ports:
            - '9200:9200'
        networks:
            - esnet
    arlas-server:
        image: gisaia/arlas-server:${ARLAS_SERVER_VERSION:-23.0.0}
        container_name: arlas-server
        environment:
            - ARLAS_ELASTIC_CLUSTER=${ES_CLUSTER:-docker-cluster}
            - ARLAS_ELASTIC_NODES=${ES_NODE:-elasticsearch:9200}
            - ARLAS_ELASTIC_ENABLE_SSL=${ES_ENABLE_SSL:-false}
            - ARLAS_ELASTIC_SNIFFING=${ES_SNIFFING:-false}
            - ARLAS_ELASTIC_CREDENTIALS=${ES_CREDENTIALS:-""}
            - ARLAS_SERVICE_WFS_ENABLE=true
            - ARLAS_CORS_ENABLED=true
            - ARLAS_SERVICE_CSW_ENABLE=true
            - ARLAS_SERVICE_RASTER_TILES_ENABLE=true
            - ARLAS_PREFIX=/arlas
            - ARLAS_ELASTIC_INDEX=${ARLAS_ELASTIC_INDEX:-.arlas}
            - ARLAS_APP_PATH=/
            - ARLAS_BASE_URI=http://${LOCAL_HOST-localhost}:81/server/
        depends_on:
            - elasticsearch
        command: ["/opt/app/wait-for-elasticsearch.sh"]
        ports:
            - '19999:9999'
        networks:
            - esnet
    arlas-permissions-server:
        image: gisaia/arlas-permissions-server:${ARLAS_PERMISSIONS_VERSION:-23.0.0}
        container_name: arlas-permissions-server
        environment:
            - ARLAS_PERMISSIONS_PORT=9996
            - ARLAS_PERMISSIONS_PREFIX=/arlas-permissions-server
            - ARLAS_PERMISSIONS_APP_PATH=/
            - ARLAS_AUTH_ENABLED=false
        expose:
            - "9996"
        ports:
            - 19996:9996
        networks:
            - esnet
    nginx:
        build: ./nginx
        ports:
            - "81:81"
        networks:
            - esnet
        links:
            - arlas-wui
            - arlas-builder
            - arlas-hub
            - arlas-server            
            - arlas-persistence-server
            - arlas-permissions-server
        depends_on:
            - arlas-wui
            - arlas-builder
            - arlas-hub
            - arlas-server            
            - arlas-persistence-server
            - arlas-permissions-server
volumes:
    esdata1:
        driver: local
networks:
    esnet:

