#!/bin/bash

export ARLAS_WUI_VERSION=24.0.0
export ARLAS_HUB_VERSION=23.1.0
export ARLAS_BUILDER_VERSION=24.0.1
export ARLAS_PERSISTENCE_VERSION=24.0.0
export ARLAS_PERMISSIONS_VERSION=24.0.0
export ARLAS_SERVER_VERSION=24.0.1
export ELASTICSEARCH_VERSION=8.7.0
export LOCAL_HOST=localhost
export ARLAS_PERSISTENCE_LOCAL_FOLDER_HOST=$HOME/.arlas/persist
