#!/bin/bash

export ARLAS_WUI_VERSION=21.0.0
export ARLAS_HUB_VERSION=21.0.0
export ARLAS_BUILDER_VERSION=21.0.0
export ARLAS_PERSISTENCE_VERSION=21.0.0
export ARLAS_PERMISSIONS_VERSION=21.0.0
export ARLAS_SERVER_VERSION=21.0.0
export LOCAL_HOST=localhost
export ARLAS_PERSISTENCE_LOCAL_FOLDER_HOST=$HOME/.arlas/persist
