#!/bin/bash

export ARLAS_WUI_VERSION=17.0.0-beta.1
export ARLAS_HUB_VERSION=16.1.0
export ARLAS_BUILDER_VERSION=17.0.0-beta.1
export ARLAS_PERSISTENCE_VERSION=16.0.1
export ARLAS_PERMISSIONS_VERSION=16.0.1
export ARLAS_SERVER_VERSION=17.7.0-beta.2
export LOCAL_HOST=localhost
export ARLAS_PERSISTENCE_LOCAL_FOLDER_HOST=$HOME/.arlas/persist