services:
  apisix:
    image: ${APISIX_VERSION}
    container_name: apisix
    depends_on:
      arlas-server:
        condition: service_healthy
      arlas-wui:
        condition: service_healthy
    restart: ${APISIX_RESTART_STRATEGY:-always}
    environment:
      - APISIX_STAND_ALONE=${APISIX_STAND_ALONE:-true}
# Exposing port 443 as apisix is the only entrypoint to the application
    ports:  # SHOULD WE OPEN 80 FOR REDIRECTION ON 443?
      - "443:9443" # !EXPOSE!
    volumes:
      - ${APISIX_CONF_DIRECTORY}/apisix.generated.yaml:/usr/local/apisix/conf/apisix.yaml:ro
      # APISIX cant start if we set read only
      - ${APISIX_CONF_DIRECTORY}/config.yaml:/usr/local/apisix/conf/config.yaml # !not read only!
    networks:
      - arlas-net
    extra_hosts:
      - ${HOST}:host-gateway
    logging:
      driver: "${DOCKER_LOGGING_DRIVER:-json-file}"
      options:
        tag: ${ARLAS_LOGGING_TAG:-arlas_logging}
