services:
  filebeat:
    image: ${FILEBEAT_VERSION}
    container_name: filebeat
    depends_on:
      elasticsearch-logs:
        condition: service_healthy
      kibana-logs:
        condition: service_healthy
    restart: ${ELASTIC_RESTART_STRATEGY:-always}
    command: filebeat -e -strict.perms=false
    user: root
    environment:
      - FILEBEAT_ELASTIC_CERT_AUTH="/usr/share/filebeat/certs/ca/ca.crt"
      - FILEBEAT_ELASTIC_CERT="/usr/share/filebeat/certs/elasticsearch-logs/elasticsearch-logs.crt"
      - FILEBEAT_ELASTIC_KEY="/usr/share/filebeat/certs/elasticsearch-logs/elasticsearch-logs.key"
      - FILEBEAT_ELASTIC_NODES="${FILEBEAT_ELASTIC_NODES:-https://elasticsearch-logs:9200}"
      - FILEBEAT_ELASTIC_PASSWORD="${ELASTIC_PASSWORD}"
      - FILEBEAT_ELASTIC_USERNAME="${FILEBEAT_ELASTIC_USERNAME:-elastic}"
      - FILEBEAT_KIBANA_CERT_AUTH="/usr/share/filebeat/certs/ca/ca.crt"
      - FILEBEAT_KIBANA_CERT="/usr/share/filebeat/certs/kibana-logs/kibana-logs.crt"
      - FILEBEAT_KIBANA_KEY="/usr/share/filebeat/certs/kibana-logs/kibana-logs.key"
      - FILEBEAT_KIBANA_NODE="${FILEBEAT_KIBANA_NODE:-https://kibana-logs:5601}"
      - FILEBEAT_KIBANA_PASSWORD="${ELASTIC_PASSWORD}"
      - FILEBEAT_KIBANA_USERNAME="${FILEBEAT_KIBANA_USERNAME:-elastic}"
    networks:
      - arlas-net
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ELASTIC_CERTS_DIRECTORY}:/usr/share/filebeat/certs
      - ${FILEBEAT_CONF_DIRECTORY}/filebeat-ilm.json:/usr/share/filebeat/filebeat-ilm.json:ro
      - ${FILEBEAT_CONF_DIRECTORY}/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ${FILEBEAT_STORAGE_DIRECTORY:-/tmp/filebeat/data}:/usr/share/filebeat/data
