services:
  arlas-wui-iam:
    image: ${ARLAS_WUI_IAM_VERSION}
    container_name: arlas-wui-iam
    depends_on:
      arlas-server:
        condition: service_healthy
      auth-server:
        condition: service_healthy
    restart: ${ARLAS_WUI_IAM_RESTART_STRATEGY:-always}
    environment:
      - ARLAS_AUTHENT_MODE=${ARLAS_AUTHENT_MODE}
      - ARLAS_AUTHENT_THRESHOLD=${ARLAS_AUTHENT_THRESHOLD}
      - ARLAS_IAM_SERVER_URL=/arlas_iam_server
      - ARLAS_TAB_NAME="ARLAS Wui IAM"
      - ARLAS_USE_AUTHENT=${ARLAS_USE_AUTHENT}
      - ARLAS_WUI_IAM_APP_PATH=/iam
      - ARLAS_WUI_IAM_BASE_HREF=/iam
    expose:
      - "80"
    networks:
      - arlas-net
