## @section Global parameters

# -- DNS domain hosting ARLAS
dnsDomain: localhost
defaultStorageClass: standard

services:
  servicePort: 8000
  serviceType: ClusterIP
  mountCertificate: false
  podSecurityContext:
    fsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
  server: 
    serviceName: arlas-server
    image: gisaia/arlas-server:27.3.3
    replicaCount: 1
    jvmXmx: 1800m
    trustStoreOptions: -Djavax.net.ssl.trustStore=/opt/app/store/arlas-ks.jks -Djavax.net.ssl.trustStorePassword=arlaspassword
    apm: false
    imagePullSecrets: []
    extraContainers: []
    extraInitContainers:
    extraEnv:
    extraVolumeMounts:
    extraVolumes:
    urlPrefix: /arlas
    publicUris: swagger.*:*,stac:GET,openapi.json:GET,stac/.*:GET/POST,explore/.*:GET/POST,persist/.*:GET,authorize/resources:GET
    resources:
      requests:
        cpu: 0.1
        memory: 256Mi
      limits:
        cpu: 1
        memory: 1000Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}

  permissions:
    serviceName: arlas-permissions-server
    image: gisaia/arlas-permissions-server:27.1.2
    replicaCount: 1
    jvmXmx: 512m
    apm: false
    imagePullSecrets: []
    extraContainers: []
    extraInitContainers:
    extraEnv:
    extraVolumeMounts:
    extraVolumes:
    urlPrefix: /permissions
    publicUris: swagger.*:*,stac:GET,openapi.json:GET,stac/.*:GET/POST,explore/.*:GET/POST,persist/.*:GET,authorize/resources:GET

    resources:
      requests:
        cpu: 0.1
        memory: 128Mi
      limits:
        cpu: 0.5
        memory: 512Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}

  persistence: 
    serviceName: arlas-persistence-server
    image: gisaia/arlas-persistence-server:27.1.1
    replicaCount: 1
    jvmXmx: 512m
    # -- Whether ES APM should be activated or not
    apm: false
    imagePullSecrets: []
    extraContainers: []
    extraInitContainers:
    extraEnv:
    extraVolumeMounts:
    extraVolumes:
    urlPrefix: /persist
    publicUris: swagger.*:*,stac:GET,openapi.json:GET,stac/.*:GET/POST,explore/.*:GET/POST,persist/.*:GET,authorize/resources:GET
    resources:
      requests:
        cpu: 0.1
        memory: 128Mi
      limits:
        cpu: 0.5
        memory: 512Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}

auth:
  checkOrganizations: false
keycloak:
  enabled: true
  realm: arlas
  client: arlas-backend
  secret: rha14c4202RB0Dxlke6ZNCCTw9gkvLJ8
  url: http://172.18.0.2/auth

# -- Cache TTL for items in cache (seconds), used for all deployments to ensure consistency
cacheTimeout: 60
# -- The factory class for the cache (io.arlas.server.core.impl.cache.HazelcastCacheFactory, io.arlas.server.core.impl.cache.LocalCacheFactory or io.arlas.server.core.impl.cache.NoCacheFactory)
cacheFactoryClass: io.arlas.server.core.impl.cache.LocalCacheFactory
# -- The java package to process for extracting the APIs displayed in Swagger
swaggerResource: io.arlas.server.rest,io.arlas.server.stac


cors:
  # cors.enabled -- Enable CORS or not
  enabled: false
  # cors.allowedOrigins -- CORS Allowed Origins
  allowedOrigins: '"*"'
  # cors.allowedHeaders -- CORS Allowed Headers
  allowedHeaders: "arlas-user,arlas-groups,arlas-organization,arlas-org-filter,X-Requested-With,Content-Type,Accept,Origin,Authorization,X-Forwarded-User"
  # cors.allowedMethods -- CORS Allowed Methods
  allowedMethods: "OPTIONS,GET,PUT,POST,DELETE,HEAD"
  # cors.allowedCredentials -- CORS Allowed Credentials or not
  allowedCredentials: true
  # cors.exposedHeaders -- CORS Exposed Headers
  exposedHeaders: "Content-Type,Authorization,X-Requested-With,Content-Length,Accept,Origin,Location,WWW-Authenticate"

logger:
  # -- Default logging level
  loggingLevel: INFO
  # -- Default console logging level
  loggingConsoleLevel: INFO

elastic:
  cluster: elastic
  login: elastic
  password: password4elastic
  skipMaster: true
  sniffing: false
  ssl:
    enabled: true
  apm:
    secret:
    url:
  nodes: elasticsearch:9200

persistence:
  # -- Storage engine to use: either `file` or `hibernate`
  engine: file
  # -- Storage size in case of file persistence
  storageSize: 100Mi
  # -- Path to use for file persistence
  localFolder: /persistence/
  
  # -- Configuration node if `engine=hibernate`, ignored otherwise
  hibernate:
    # -- JDBC URL
    url: jdbc:postgresql://db:5432/arlas
    # -- Database user login
    user:
    # -- Database user password
    password:
    # -- SQL Dialect
    dialect: org.hibernate.dialect.PostgreSQLDialect
    # -- JDBC Driver
    driver: org.postgresql.Driver

subServices:
  # -- Whether INSPIRE Service is activated or not
  inspireActivated: '"false"'
  # -- Whether Raster Tile Service is activated or not
  rasterTileActivated: '"false"'
  # -- Whether CSW Service is activated or not
  cswActivated: '"false"'
  # -- Whether WFS Service is activated or not
  wfsActivated: '"false"'
