{{- if and .Values.keycloak.ingress.enabled .Values.deployment.keycloak.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    {{- toYaml .Values.keycloak.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.keycloak.ingress.ingressClassName | quote }}
  tls:
    - hosts:
        - {{ .Values.keycloak.ingress.hostname | quote }}
      secretName: {{ .Values.keycloak.ingress.tls.secretName | quote }}
  rules:
    - host: {{ .Values.keycloak.ingress.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.keycloak.ingress.path | quote }}
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: {{ .Values.keycloak.http.port }}
{{- end }}