{{- if .Values.deployment.aias.services.titiler.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arlas-titiler-ingress
  annotations:
    {{ .Values.deployment.aias.services.titiler.ingress.annotations | toYaml | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
    - host: {{ .Values.global.dnsDomain }}
      http:
        paths:
          - path: /colorMaps
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.deployment.aias.services.titiler.serviceName }}
                port:
                  number: {{ .Values.deployment.aias.services.titiler.port }}

          - path: /cog/preview
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.deployment.aias.services.titiler.serviceName }}
                port:
                  number: {{ .Values.deployment.aias.services.titiler.port }}
          - path: /cog/statistics
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.deployment.aias.services.titiler.serviceName }}
                port:
                  number: {{ .Values.deployment.aias.services.titiler.port }}
          - path: /cog/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.deployment.aias.services.titiler.serviceName }}
                port:
                  number: {{ .Values.deployment.aias.services.titiler.port }}
{{- end }}
