
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arlas-ingress
  namespace: arlas
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100240m
    blackbox.monitoring/enabled: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"  # Disable buffering
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
    - host: {{ .Values.global.dnsDomain }}
      http:
        paths:
          - backend:
              service:
                name: arlas-stack-apisix-data-plane
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
 