{{- if .Values.deployment.aias.uis.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arlas-wui-ingress
  annotations:
    {{ .Values.deployment.aias.uis.ingress.annotations | toYaml | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
    - host: {{ .Values.global.dnsDomain }}
      http:
        paths:
          - path: /wui/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ (get .Values "arlas-uis").uis.wui.serviceName }}
                port:
                  number: {{ (get .Values "arlas-uis").uis.servicePort }}
{{- end }}
