{{- if .Values.deployment.aias.services.airs.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arlas-airs-ingress
  annotations:
    {{ .Values.deployment.aias.services.airs.ingress.annotations | toYaml | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
    - host: {{ .Values.global.dnsDomain }}
      http:
        paths:
          - path: /airs/collections
            pathType: Prefix
            backend:
              service:
                name: {{ (get .Values "aias-services").services.airs.serviceName }}
                port:
                  number: {{ (get .Values "aias-services").services.servicePort }}
{{- end }}
