{{- if .Values.deployment.elasticsearch.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-ingress
  namespace: arlas
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100240m
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    blackbox.monitoring/enabled: "true"
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
    - host: {{ .Values.global.elasticDnsDomain }}
      http:
        paths:
          - backend:
              service:
                name: arlas-stack-elasticsearch
                port:
                  number: 9200
            path: /
            pathType: ImplementationSpecific
 {{- end }}
