## @section Global parameters

# -- DNS domain hosting ARLAS
dnsDomain: localhost

serviceName: arlas-wui
servicePort: 8080
serviceType: ClusterIP
image: gisaia/arlas-wui:27.0.5


persistence:
  urlPrefix: /arlas/persistence

permissions:
  urlPrefix: /arlas/permissions

wuiHub:
  # wuiHub.baseAppPath -- Base URL path
  baseAppPath: /arlas/wui/hub

wuiAuthent:
  # -- When authentication is enabled, this option forces to be connected to Identity Provider at application bootstrap
  forceConnect: false
  # -- Defines whether to be authenticated to Identity Provider
  useAuthent: true
  # -- Defines authentication mode (i.e. "iam", "openid" or not defined)
  authMode: openid
  # -- Refresh token timer (arlas iam)
  threshold: 60000
  # -- Defines whether we use Identity Provider document discovery service
  useDiscovery: true
  #-- The requested scopes
  scope: profile
  # -- Custom query params
  customQueryParams:
    - audience: http://arlas.io/api/server
  # -- Defines whether https is required
  requireHttps: true
  # -- Response type values
  responseType: code
  # -- Timeout for silent refresh
  silentRefreshTimeout: "10000"
  # -- Defines when the token_timeout event should be raised. If you set this to the default value 0.75, the event s triggered after 75% of the token's life time.
  timeoutFactor: "0.75"
  # -- If true, the app will try to check whether the user is still logged in on a regular basis as described
  sessionChecksEnabled: true
  # -- Defines whether to clear the hash fragment in url after logging in
  clearHashAfterLogin: true
  # -- This property has been introduced to disable at_hash checks and is indented for Identity Provider that does not deliver an at_hash EVEN THOUGH its recommended by the OIDC specs.
  disableAtHashCheck: true
  # -- Defines whether to display debug log in browser console
  showDebugInformation: false
  # -- Defines the kind of storage: localstorage or sessionstorage
  storage: memorystorage
  # -- The issuer's uri
  issuer: 
  # -- The logout URL to be used
  logoutUrl:
  # -- The client's id as registered with the auth server
  clientId:

wui:
  # -- Base URL path
  baseAppPath: /arlas/wui
  # -- List of links to be added in the left menu of the WUI. Each link must contain `icon`, `url` and `name` attributes.
  links: []
  # -- The Google Analytics key of the wui app
  googleAnalyticsKey:
  # -- Version number of the ARLAS Hits Exporter to use
  hitsExporterVersion: 2.2
  # -- The text to display on the tab of the web browser (will be enriched with the dashboard name)
  tabName: ARLAS Exploration
  # -- Whether to display the dashboard shortcut icon
  dashboardShortcut: false
  # -- Whether or not to enable result list export
  resultListEnableExport: false
  # -- Result list export size
  resultListExportSize: 1000
  # -- Maximum number of buckets for the histogram graph
  histogramsMaxBucket: 200
  # -- Maximum number of buckets for the histogram export
  histogramsExportNbBuckets: 1000
  # -- Enable or disable Geocoding feature
  enableGeocoding: false
  # -- Geocoding find place URL
  geocodingUrl:
  # -- Maximum zoom level for geocoding feature
  geocodingZoomTo: 11
  configuration: {}

actionsEnv:
  # -- Relative AIAS download execution URL
  - name: ARLAS_DOWNLOAD_PROCESS_URL
    value: /aproc/processes/download/execution
  # -- Relative AIAS download URL
  - name: ARLAS_DOWNLOAD_PROCESS_CHECK_URL
    value: /aproc/processes/download
  # -- AIAS download max number of items
  - name: ARLAS_DOWNLOAD_PROCESS_MAX_ITEMS
    value: "100"
  # -- AIAS download configuration file location
  - name: ARLAS_DOWNLOAD_PROCESS_SETTINGS_URL
    value: assets/processes/download.json
  # -- AIAS download status relative url
  - name: ARLAS_DOWNLOAD_PROCESS_STATUS_URL
    value: /aproc/jobs
  # -- Relative AIAS enrich execution URL
  - name: ARLAS_ENRICH_PROCESS_URL
    value: /aproc/processes/enrich/execution
  # -- Relative AIAS enrich URL
  - name: ARLAS_ENRICH_PROCESS_CHECK_URL
    value: /aproc/processes/enrich
  # -- AIAS enrich max number of items
  - name: ARLAS_ENRICH_PROCESS_MAX_ITEMS
    value: "100"
  # -- AIAS enrich configuration file location
  - name: ARLAS_ENRICH_PROCESS_SETTINGS_URL
    value: assets/processes/enrich.json
  # -- AIAS enrich status relative url
  - name: ARLAS_ENRICH_PROCESS_STATUS_URL
    value: /aproc/jobs

basemap:
  # -- Size of the directory containing the basemap files
  storageSize: 10Mi

# -- Number of desired pods
replicaCount: 1

resources:
  requests:
    cpu: 0.05
    memory: 10Mi
  limits:
    cpu: 0.3
    memory: 30Mi

logger:
  # -- Default logging level
  loggingLevel: INFO
  # -- Default console logging level
  loggingConsoleLevel: INFO


# -- Label-based selector, to control the nodes the pod(s) will run on. See https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}
# -- Pod-Tolerations & Nodes-Taints work together to allow nodes to repel certain kinds of pods. See https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []
# -- Allows constraining pod(s) to only run on particular nodes, or to prefer to run on particular nodes. It is based on label-selection. See https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

