apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: {{ .Values.services.airs.serviceName }}
  name: {{ .Values.services.airs.serviceName }}
spec:
  replicas: {{ int .Values.services.airs.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.services.airs.serviceName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ .Values.services.airs.serviceName }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.services.airs.serviceName }}
          image: {{ .Values.services.airs.image }}
          ports:
            - name: http
              containerPort: {{ .Values.services.servicePort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.services.airs.urlPrefix }}/healthcheck
              port: {{ .Values.services.servicePort }}
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: {{ .Values.services.airs.urlPrefix }}/healthcheck
              port: {{ .Values.services.servicePort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          resources:
            {{- toYaml .Values.services.airs.resources | nindent 12 }}
          env:

            # ENDPOINT CONFIGURATION              
            - name: AIRS_CORS_HEADERS
              value: {{ .Values.cors.allowedHeaders | quote }}
            - name: AIRS_CORS_METHODS
              value: {{ .Values.cors.allowedMethods | quote }}
            - name: AIRS_CORS_ORIGINS
              value: {{ .Values.cors.allowedOrigins | squote }}
            - name: AIRS_HOST
              value: {{ .Values.cors.allowedHosts | squote }}

            - name: AIRS_PORT
              value: {{ .Values.services.servicePort | quote }}
            - name: AIRS_PREFIX
              value: {{ .Values.services.airs.urlPrefix }}

            # LOGGING
            - name: AIRS_LOGGER_LEVEL
              value: {{ .Values.logger.loggingLevel }}
            - name: ACCESS_LOGGER_LEVEL
              value: {{ .Values.logger.loggingLevel }}

          volumeMounts:
            - name: airs-files
              mountPath: /app/conf/
              readOnly: true
      volumes:
        - name: airs-files
          configMap:
            name: airs-files-configmap

      # NODE SELECTION      
      {{- with .Values.services.airs.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.airs.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.services.airs.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
