## @section Global parameters

# -- DNS domain hosting ARLAS
dnsDomain: localhost
protocol: http
defaultStorageClass: standard

uis:
  servicePort: 8080
  serviceType: ClusterIP

  wui:
    serviceName: arlas-wui
    image: gisaia/arlas-wui:27.1.3
    # -- Extra environment variables for the arlas wui container
    extraEnvVars:
    urlPrefix: /wui
    tabName: ARLAS Exploration
    basemapUrl: 
  famWui:
    serviceName: arlas-fam-wui
    image: gisaia/arlas-fam-wui:0.9.4
    # -- Extra environment variables for the arlas fam wui container
    extraEnvVars:
    urlPrefix: /fam-wui
    tabName: ARLAS FAM Wui
    famDefaultURL:
    collectionName: main
    catalog: main catalog
    archivePageSize: 10
    filePageSize: 50
 
  hub:
    serviceName: arlas-hub
    image: gisaia/arlas-wui-hub:27.1.2
    # -- Extra environment variables for the arlas hub container
    extraEnvVars:
    urlPrefix: /hub
    tabName: ARLAS Hub

  builder: 
    serviceName: arlas-builder
    image: gisaia/arlas-wui-builder:27.1.2
    # -- Extra environment variables for the arlas builder container
    extraEnvVars:
    urlPrefix: /builder/
    tabName: ARLAS Studio
    allowExternalNodeConfiguration: true
    advancedFeatures: false
    # @ignored
    basemaps: '[
        {"name":"Contrast","url":"/wui/assets/basemap/styles/protomap-contrast.json","image":"/wui/assets/basemap/quicklook/contrast.png", "type": "protomap"},
        {"name":"Dark","url":"/wui/assets/basemap/styles/protomap-dark.json","image":"/wui/assets/basemap/quicklook/dark.png", "type": "protomap"},
        {"name":"Grayscale","url":"/wui/assets/basemap/styles/protomap-grayscale.json","image":"/wui/assets/basemap/quicklook/grayscale.png", "type": "protomap"},
        {"name":"Light","url":"/wui/assets/basemap/styles/protomap-light.json","image":"/wui/assets/basemap/quicklook/light.png", "type": "protomap"},
        {"name":"White","url":"/wui/assets/basemap/styles/protomap-white.json","image":"/wui/assets/basemap/quicklook/white.png", "type": "protomap"}
        ]'
  colors:
    arlas:
      bg: "#ff4081"
    handle:
      color: "#ff4081"
  logoImagePng60x60Base64: iVBORw0KGgoAAAANSUhEUgAAADwAAAA8CAYAAAA6/NlyAAAHy0lEQVRoQ+1ae1QUZRy9s7u8XWBX2zWFEgRJMFGnh+gxUzMr83GwjZNlPjJ6kK8Sy+RAatYpK7WHJpGGZXXK8FT2kDQ7Hk0tXkKKKS9tF3aDFpBdkMcynQGUhd2d+WZmVzonv3/n3vv73fl9M9+Twv+sUf8zv7hm2IMV94n16z/An/LR0IHqIIqxKfStjdYL1qa/9c1/G01AIwDGg/E7pD1W4eiAgIEp2ttW3B805FGlzEtLEsvGMJacxur9a435G36oO5/vCfPuNqz4OGxS6lx1xPMyUN4SE2ZyG6u/m1V8YIEBDf9I1LpCd5dh+YFh0zOmKAcvcFdi9jo1rZeK48qyJpZYLNVS9SUbfnkwPX/NQHonSZeVmmyeteYr+kyWTsq3LsWwwhg7r0ir8LtJqhEhfAZou+PsdzFHGgxnhfAuY0UZpn1VN+TE6MoAyMUEdQdno6lw6Sr98XeEagk2vEAdMXZn2ORjQgN5Ar+3tnx7fNlPTwrRFmT4GVXU+HfCJx4REsDT2L21FTviy7IfI41DbHhykGbowYjZJaTCVxO3x3wuVVd+aD1JTFLDPgydaO3Lb5bPTELpoYlf1J07zIcjMmweNb9UJfcJ5xMjfu4lB1ptxHBCYDuVm+4PoJkLz2v49dCxTyVrRm4lDEoGy0gGVr0PmBvI8IQoQ4s1L6RoNy3FsIKhE1vcOqkIDAB+fgsoNwK6NEIr5LA55dlxWeaK464YnBX+JmLajhlBNy4kD0eAzFwNxAzpBM5cA1TWEJDIIa1Me713XkawGMPur25wP+DAm925VP4DzHyR3A0hUld+cPwec+mvzuAuK7wlNG7lUs3NGwljkMF2pwBRoT2xD6QBFUYyPiGq3tZSEVzwUZggwy1jFl/0omRKwhj8MJUS+OkNR1xNPXDPKn6+QMTg3PSAys5NhR7NaYXDoQoqpXV1AmNww51V9zLjkQ3AmQs9+XI5YBM/dL1ZdTJpZeUJh9HFqeFXB9369AvXj37PbYaDAoCDb7mWq20Apq7sfq5VAS8tAJ7aJDqFOltzmaogcyhRhQ0jH8kf5OU/SnS03kT7P7Mr0UWvAYXsAgzAvleBgWpg0gqgwaFXkqbFULnpMiLDbfTjl+SgfEiVOXG9/8yuwPVWYMqzwJhIIL2r2gUlwGLx/01NbrqyGrDYh3TWpWUMnSj+4+ltaNeLQPSNZO+O7cKbkgBfu+0w9iWwL0NEm1LyLf1zfVUep2EtEGCkE3u8FRGxOinqQCBbQIUYBqB61YD9mbE/NRFtvSF/Yarx9484DdP+A67PGR5fKUIfmD8NyNzfTd29Boi6QZRUDxI7bLHDl8D2hrFofbLhWCqn4Zt9teGFMbNKBWp3ThfZn9PdyYD5IqBWAtlOxl3BwuicmLATFIHtoKXy7bv+3LeM0/Ao3+Ah+TEPlgvUBg5tApT+QHUdcO/zwK7VQHTXnFmwmBPC7BRAL2yXlsjwyH5azcmoWSZBOY4fAWxZ0k3Z/i3wxAxBErxgoxm4fzUvzB6woSo/LaXy93WcFQbgx9CJwga/o+8CPl6CkhEFTlgHlBqIqev0eXPTTDmf8RmmuoYl3s2BDqEZ44C0+cRJSALWW4ApzxFLTP7zxxGHLBdO8RlG25jHrXKKYrdL+NuJbYDcYULDzxOLsJ+R8WiE5ab7VQCXeA2fjtEdHu6rmsCb07y7gWVzeGFuBViagDuXk0jaqNx0RW+g0267TDsiYXPIuM85VdkJwm/bHCcKJKlIxSRtBk4Uc6oYWq0FIYW7RxMZHgL4ltOJTZyKS+OBR6dJTV0cv6kZmLCUk7vCcFS32XhqD5FhFmQZvcgYIFOwB9mOjf1m2W+3L9uz7wGHC11mQOWms8NGG7HhZG1swushtzvv1msXAtPH9qVdoKUNGJfkNIeKloYTYUWfOU2Qa+ih2unEVqr3CaGXonsj7gqbcn15ouPWRtfVDfsbHCTcK1QX/NSdwC8FDqYnlHw99Ei9qWtx3fMx51i7K3zS6nmqyFf6tpTCotfamkvUBZmRrlh8kwu2ypcoQOp9DWFZS0DHnt4TWthk1os1jAdUYRO+DJ/Ke0glIUe3UY9bTZ/Gnfn6YS5Bvgp3cPOHz/l+lH//e92WmQeE2ph2q1deBrutzHnXi8gwe7bUPGax2ZuSuTzC8IAHQZLRxVmDihtrqvhIpIYxCPA30IkX/4tnxEnlh6dtNZ/J5jPLPic2zIIj+vW77lzUXPZc5CquFrhtvGsqWrxEf+xDErOCDbOEm5TK/qeHPWSkAIeJOWlQd+GSzh+du7XmVI/1Lp+2oArbiXk3jl70l59MoeEL4KHnzIyS/bfsqz/fYwuWJJZYwx3a2ZH37ZgaGOLe82OerK3tbfoR+Tsie69zScyK6tK9hW8PvC7yaMTsHDlFBZIGFYljtpj+eGK5/tcPRPI7aJIqbB94rTY2ISXktkyZu45ousWZrNqy9+eUHXgGQLsUs241fDkRnToibmvouJ0DFL5RUpJrZWy1G6tOvrCmKifDHUYv5+K2CjsxJ4tXDY1brolecqu/ZrKPTK52WHnZVbGVaW8qab6Y90nN2W27TAV79QD3BoTIt+lJw85SkocA3goEd5xMWuHVVo1qdpPNYaEu0g8v7Wob5k3I04Brhj39hvta/1qF+7oCno7/LwubSFtDfZRBAAAAAElFTkSuQmCC
  spinnerGifBase64: 
  noViewPngBase64: 
  logoInnerPngBase64: 
    
services:
  server:
    urlPrefix: /arlas
  persistence:
    urlPrefix: /persist
  permissions:
    urlPrefix: /permissions
  aprocService:
    urlPrefix: /aproc
  airs:
    urlPrefix: /airs
  fam:
    urlPrefix: /fam

# -- List of links to be added in the left menu of the WUI. Each link must contain `icon`, `url` and `name` attributes.
links: '
        [
            {
                "name":"Hub",
                "url":"/hub/",
                "icon":"hub",
                "check_url": "/persist/healthcheck"
            },
            {
                "name": "Import",
                "icon": "folder",
                "url": "/fam-wui/",
                "check_url": "/fam/healthcheck",
                "check_url_response_type": "text"
            }
        ]'
# -- The Google Analytics key of the wui app
googleAnalyticsKey:
# -- Version number of the ARLAS Hits Exporter to use
hitsExporterVersion: 2.2
# -- The text to display on the tab of the web browser (will be enriched with the dashboard name)
# -- Whether to display the dashboard shortcut icon
dashboardShortcut: false
# -- Whether or not to enable result list export
resultListEnableExport: false
# -- Result list export size
resultListExportSize: 1000
# -- Maximum number of buckets for the histogram graph
histogramsMaxBucket: 200
# -- Maximum number of buckets for the histogram export
histogramsExportNbBuckets: 1000
# -- Enable or disable Geocoding feature
enableGeocoding: false
# -- Geocoding find place URL
geocodingUrl:
# -- Maximum zoom level for geocoding feature
geocodingZoomTo: 11
configuration: {}

authent:
  # -- When authentication is enabled, this option forces to be connected to Identity Provider at application bootstrap
  forceConnect: true
  # -- Defines whether to be authenticated to Identity Provider
  useAuthent: true
  # -- Defines authentication mode (i.e. "iam", "openid" or not defined)
  authMode: openid
  # -- Refresh token timer (arlas iam)
  threshold: 60000
  # -- Defines whether we use Identity Provider document discovery service
  useDiscovery: true
  #-- The requested scopes
  scope: profile
  # -- Custom query params
  customQueryParams:
    - audience: http://arlas.io/api/server
  # -- Defines whether https is required
  requireHttps: false
  # -- Response type values
  responseType: code
  # -- Timeout for silent refresh
  silentRefreshTimeout: "1000"
  # -- Defines when the token_timeout event should be raised. If you set this to the default value 0.75, the event s triggered after 75% of the token's life time.
  timeoutFactor: "0.75"
  # -- If true, the app will try to check whether the user is still logged in on a regular basis as described
  sessionChecksEnabled: true
  # -- Defines whether to clear the hash fragment in url after logging in
  clearHashAfterLogin: true
  # -- This property has been introduced to disable at_hash checks and is indented for Identity Provider that does not deliver an at_hash EVEN THOUGH its recommended by the OIDC specs.
  disableAtHashCheck: true
  # -- Defines whether to display debug log in browser console
  showDebugInformation: false
  # -- Defines the kind of storage: localstorage or sessionstorage
  storage: memorystorage
  # -- The issuer's uri
  issuer: 
  # -- The logout URL to be used
  logoutUrl:
  # -- The client's id as registered with the auth server
  clientId: arlas-front

basemap:
  # -- Size of the directory containing the basemap files
  storageSize: 10Mi

# -- Number of desired pods
replicaCount: 1

resources:
  requests:
    cpu: 0.05
    memory: 10Mi
  limits:
    cpu: 0.1
    memory: 50Mi

logger:
  # -- Default logging level
  loggingLevel: INFO
  # -- Default console logging level
  loggingConsoleLevel: INFO


# -- Label-based selector, to control the nodes the pod(s) will run on. See https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}
# -- Pod-Tolerations & Nodes-Taints work together to allow nodes to repel certain kinds of pods. See https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []
# -- Allows constraining pod(s) to only run on particular nodes, or to prefer to run on particular nodes. It is based on label-selection. See https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

