## @section Global parameters

# -- DNS domain hosting ARLAS
dnsDomain: localhost

serviceName: airs-server
servicePort: 8000
serviceType: ClusterIP

image: gisaia/airs:0.6.31

# -- Number of desired pods
replicaCount: 1

# -- Whether ES APM should be activated or not
apm: false

# -- Base URL path for the server's general API
urlPrefix: /airs

# -- Name of the organization using AIAS
organization: org.com

# -- Prefix appended to elasticsearch indices containing AIRS collections. The final name is of the form: prefix@organization_indexname
airsIndexPrefix: airs

resources:
  requests:
    cpu: 0.1
    memory: 10Mi
  limits:
    cpu: 1
    memory: 500Mi

cors:
  # cors.allowedOrigins -- CORS Allowed Origins
  allowedOrigins: '"*"'
  # cors.allowedHeaders -- CORS Allowed Headers
  allowedHeaders: "arlas-user,arlas-groups,arlas-organization,arlas-org-filter,X-Requested-With,Content-Type,Accept,Origin,Authorization,X-Forwarded-User"
  # cors.allowedMethods -- CORS Allowed Methods
  allowedMethods: "OPTIONS,GET,PUT,POST,DELETE,HEAD"
  # cors.allowedMethods -- Allowed hosts
  allowedHosts: "0.0.0.0"
  # cors.allowedCredentials -- CORS Allowed Credentials or not
  allowedCredentials: true
  # cors.exposedHeaders -- CORS Exposed Headers
  exposedHeaders: "Content-Type,Authorization,X-Requested-With,Content-Length,Accept,Origin,Location,WWW-Authenticate"

logger:
  # -- Default logging level
  loggingLevel: INFO
  # -- Default console logging level
  loggingConsoleLevel: INFO

elastic:
  cluster: elastic
  login: elastic
  password: elastic
  apm:
    secret:
    url:

# -- Extra environment variables to send to elasticsearch container
elasticEnv:

# -- Configuration of the s3 used for storing and accessing the STAC collections, items and managed assets
s3:
  # -- s3 key
  accessKeyId: airs
  # -- s3 secret
  secret: airssecret
  # -- s3 endpoint
  endpoint: http://minio:9000
  # -- asset_http_endpoint_url_pattern must look like https://storage.googleapis.com/{}/{} where first {} is the bucket, second {} is the path to the object  
  assetHttpEndpointUrlPattern: "http://minio:9000/{}/{}"
  # -- s3 bucket name for storing the STAC collections, items and managed assets
  bucket: airs-storage
  # -- Platform type. This value is provided in the item properties
  platform: MINIO
  # -- Region. This value is provided in the item properties
  region: Standard
  # -- Tier. This value is provided in the item properties
  tier: Standard

# -- This elasticsearch mapping is used during the initialization of the index of a newly created collection
arlasMappingUrl: https://raw.githubusercontent.com/gisaia/ARLAS-EO/v0.0.9/mapping.json

# -- Label-based selector, to control the nodes the pod(s) will run on. See https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}
# -- Pod-Tolerations & Nodes-Taints work together to allow nodes to repel certain kinds of pods. See https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []
# -- Allows constraining pod(s) to only run on particular nodes, or to prefer to run on particular nodes. It is based on label-selection. See https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
