apiVersion: v2
name: arlas-aias
description: A Helm Chart to deploy the ARLAS Exploration Stack with AIAS services
version: 0.0.1

dependencies:
# ARLAS BACKEND DEPENDENCIES

- name: arlas-server
  version: 0.0.1
  repository: "file://../arlas-server"
- name: airs-server
  version: 0.0.1
  repository: "file://../airs-server"
- name: agate
  version: 0.0.1
  repository: "file://../agate"
- name: fam
  version: 0.0.1
  repository: "file://../fam"
- name: arlas-persistence-server
  version: 0.0.1
  repository: "file://../arlas-persistence-server"

# ARLAS FRONTEND DEPENDENCIES
- name: arlas-wui
  version: 0.0.1
  repository: "file://../arlas-wui"
- name: arlas-hub
  version: 0.0.1
  repository: "file://../arlas-hub"

# THIRD PARTY DEPENDENCIES
- name: elasticsearch
  repository: https://charts.bitnami.com/bitnami
  version: 22.0.4
- name: minio
  repository: https://charts.bitnami.com/bitnami
  version: 16.0.10
- name: apisix
  repository: https://charts.bitnami.com/bitnami
  version: 5.0.3
- name: rabbitmq
  repository: https://charts.bitnami.com/bitnami
  version: 16.0.11
- name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 21.2.13
