
dnsDomain: localhost


# ARLAS SERVER
arlas-server:
  dnsDomain: localhost

# ELASTICSEARCH
elasticsearch:
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0


# AIRS
airs-server:
  enabled: false
  s3.accessKey: admin
  s3.secret: changeme

minio:
  auth:
    rootUser: admin
    rootPassword: changeme

