global: 
  # -- DNS domain hosting ARLAS
  dnsDomain: &globalDnsDomain localhost

  # -- The issuer's uri
  authIssuer: &gloablAuthIssuer https://mymachine:9443/auth/realms/arlas
  # -- The logout URL to be used
  logoutUrl: &gloablLogoutUrl 
  # -- The client's id as registered with the auth server
  clientId: &globalClientId arlas-front

  # -- Name of the organization using AIAS
  organization: &globalOrganization org.com

  # -- Elasticsearch login for elasticsearch itself and the services that are connecting to elasticsearch
  elasticLogin: &globalElasticLogin elastic
  # -- Elasticsearch password for elasticsearch itself and the services that are connecting to elasticsearch
  elasticPassword: &globalElasticPassword password4elastic

  # -- Minio login for minio itself and the services that are connecting to minio
  minioLogin: &globalMinioLogin minioadmin
  # -- Minio password for minio itself and the services that are connecting to minio
  minioPassword: &globalMinioPassword secret4minio

# -- 
# -- 
# -- 


# ARLAS SERVER
arlas-server:
  # @ignored
  dnsDomain: *globalDnsDomain
  # @ignored
  elastic:
    login: *globalElasticLogin
    password: *globalElasticPassword
  logger:
    # -- Logging level
    loggingLevel: INFO
    # -- Console logging level
    loggingConsoleLevel: INFO


# ARLAS WUI
arlas-wui:
  # @ignored
  issuer: *gloablAuthIssuer
  # @ignored
  logoutUrl: *gloablLogoutUrl
  # @ignored
  clientId: *globalClientId
  logger:
    # -- Logging level
    loggingLevel: INFO
    # -- Console logging level
    loggingConsoleLevel: INFO
  # -- Set to 120 Gi if you copy the full basemap
  basemap:
    storageSize: 50Mi

# AIRS SERVER
airs-server:
# @ignored
  dnsDomain: *globalDnsDomain
# @ignored
  s3:
    accessKey: *globalMinioLogin
    secret: *globalMinioPassword
  # @ignored
  elastic:
    login: *globalElasticLogin
    password: *globalElasticPassword
  logger:
    # -- Logging level
    loggingLevel: INFO
    # -- Console logging level
    loggingConsoleLevel: INFO
  # @ignored
  organisation: *globalOrganization

# ELASTICSEARCH
# @ignored
elasticsearch:
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
  security:
    enabled: true
    elasticPassword: *globalElasticPassword
    tls:
      # AutoGenerate TLS certs for elastic
      autoGenerated: true

# @ignored
minio:
  auth:
    rootUser: *globalMinioLogin
    rootPassword: *globalMinioPassword
