{{- if .Values.deployment.rabbitmq.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: arlas-rabbitmq-default-user
  labels:
    app.kubernetes.io/name: arlas-rabbitmq
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.auth.username | quote }}
  password: {{ .Values.rabbitmq.auth.password | quote }}
  default_user.conf: |
    default_user = {{ .Values.rabbitmq.auth.username }}
    default_pass = {{ .Values.rabbitmq.auth.password }}
{{- end }}