{{- if .Values.deployment.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.service.serviceName }}-secret
type: Opaque
stringData:
  redis-password: {{ .Values.redis.password | quote }}
{{ end }}