apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: arlas-server
  name: arlas-server
spec:
  ports:
    - name: "9999"
      port: 9999
      targetPort: 9999
  selector:
    app.kubernetes.io/component: arlas-server
