{{- if .Values.deployment.seaweedfs.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: seaweedfs-configure-s3
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: weed-shell
          image: chrislusf/seaweedfs:4.48
          env:
            - name: MASTER
              value: "{{ .Values.deployment.aias.services.seaweedfs.masterServiceName }}:{{.Values.deployment.aias.services.seaweedfs.masterServicePort }}"
            - name: FILER
              value: "{{ .Values.deployment.aias.services.seaweedfs.filerServiceName }}:{{ .Values.deployment.aias.services.seaweedfs.filerServicePort }}"
            - name: LOGIN
              value: {{ .Values.global.seaweedFSLogin }}
            - name: PASSWORD
              value: {{ .Values.global.seaweedFSPassword }}
            - name: AIRS_BUCKET
              value: {{ (get .Values "aias-services").services.airs.configuration.s3.bucket | quote }}
            - name: OUTBOX_BUCKET
              value: {{ (get .Values "aias-services").services.aproc.configuration.extensions.download.outboxS3.bucket | quote }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "⏳ Waiting for SeaweedFS Cluster..."
              until wget -q -O /dev/null "http://$MASTER/cluster/status"; do sleep 5; done
              until wget -q -O /dev/null "http://$FILER/"; do sleep 5; done

              echo "🔐 Configure S3 identities..."
              weed shell -master=$MASTER -filer=$FILER <<EOF
              s3.configure -user=$LOGIN -access_key=$LOGIN -secret_key=$PASSWORD -actions=Admin,Read,Write,List,Tagging -apply
              s3.configure -user=anonymous -buckets=$AIRS_BUCKET,$OUTBOX_BUCKET -actions=Read,List -apply
              s3.configure
              EOF
{{- end }}