ARG  FROM_IMAGE=gisaia/arlas-server:latest
FROM ${FROM_IMAGE}

COPY conf/server.crt server.crt
RUN [\
 "/usr/lib/jvm/java-17-openjdk-amd64/bin/keytool",\
 "-import",\
 "-trustcacerts",\
 "-cacerts",\
 "-noprompt",\
 "-storepass",\
 "changeit",\
 "-alias",\
 "arlas-cert",\
 "-file",\
 "server.crt"\
]

ENV JDK_JAVA_OPTIONS="-Xmx1g -XX:+ExitOnOutOfMemoryError -Dcom.sun.net.ssl.checkRevocation=false"
CMD ["arlas-server.jar", "server", "/opt/app/configuration.yaml"]
