services:
  rabbitmq:
    extends:
      file: ref-dc-logger.yaml
      service: log-rotated
    image: ${ARLAS_VERSION_RABBITMQ}
    container_name: rabbitmq
    restart: always
    expose:
      - "5672"
    networks:
      - arlas-net
    volumes:
      - arlas-data-rabbimq:/var/lib/rabbitmq/mnesia
    healthcheck:
      test: "rabbitmq-diagnostics check_port_connectivity"
      interval: 10s
      timeout: 10s
      retries: 10
