services:
  arlas-hub: # ARLAS Hub is the interface for discovering all the available ARLAS Dashboards
    image: ${ARLAS_HUB_VERSION}
    container_name: arlas-hub
    depends_on:
      arlas-persistence-server:
        condition: service_healthy
    restart: ${ARLAS_HUB_RESTART_STRATEGY:-always}
    environment:
      - ARLAS_AUTHENT_CLEAR_HASH=${ARLAS_AUTHENT_CLEAR_HASH:-true}
      - ARLAS_AUTHENT_CLIENT_ID=${ARLAS_AUTHENT_CLIENT_ID:-}
      - ARLAS_AUTHENT_DISABLE_AT_HASH_CHECK=${ARLAS_AUTHENT_DISABLE_AT_HASH_CHECK:-true}
      - ARLAS_AUTHENT_ENABLE_SESSION_CHECKS=${ARLAS_AUTHENT_ENABLE_SESSION_CHECKS:-true}
      - ARLAS_AUTHENT_FORCE_CONNECT=${ARLAS_AUTHENT_FORCE_CONNECT}
      - ARLAS_AUTHENT_ISSUER=${ARLAS_AUTHENT_ISSUER}
      - ARLAS_AUTHENT_LOGOUT_URL=${ARLAS_AUTHENT_LOGOUT_URL}
      - ARLAS_AUTHENT_MODE=${ARLAS_AUTHENT_MODE}
      - ARLAS_AUTHENT_REDIRECT_URI=${ARLAS_AUTHENT_REDIRECT_URI}
      - ARLAS_AUTHENT_REQUIRE_HTTPS=${ARLAS_AUTHENT_REQUIRE_HTTPS:-false}
      - ARLAS_AUTHENT_RESPONSE_TYPE=${ARLAS_AUTHENT_RESPONSE_TYPE}
      - ARLAS_AUTHENT_SCOPE=${ARLAS_AUTHENT_SCOPE}
      - ARLAS_AUTHENT_SHOW_DEBUG=${ARLAS_AUTHENT_SHOW_DEBUG:-false}
      - ARLAS_AUTHENT_SILENT_REFRESH_REDIRECT_URI=${ARLAS_AUTHENT_SILENT_REFRESH_REDIRECT_URI}
      - ARLAS_AUTHENT_SILENT_REFRESH_TIMEOUT=${ARLAS_AUTHENT_SILENT_REFRESH_TIMEOUT:-10000}
      - ARLAS_AUTHENT_STORAGE=${ARLAS_AUTHENT_STORAGE:-memorystorage}
      - ARLAS_AUTHENT_THRESHOLD=${ARLAS_AUTHENT_THRESHOLD}
      - ARLAS_AUTHENT_TIMEOUT_FACTOR=${ARLAS_AUTHENT_TIMEOUT_FACTOR:-0.75}
      - ARLAS_AUTHENT_USE_DISCOVERY=${ARLAS_AUTHENT_USE_DISCOVERY}
      - ARLAS_BUILDER_URL=${ARLAS_BUILDER_URL:-/builder/}
      - ARLAS_HUB_BASE_HREF=${ARLAS_HUB_BASE_HREF:-/hub}
      - ARLAS_IAM_SERVER_URL=${ARLAS_IAM_SERVER_URL:-/arlas_iam_server}
      - ARLAS_PERMISSIONS_URL=${ARLAS_PERMISSIONS_URL:-/arlas_permissions_server}
      - ARLAS_PERSISTENCE_URL=${ARLAS_PERSISTENCE_URL:-/persist}
      - ARLAS_USE_AUTHENT=${ARLAS_USE_AUTHENT}
      - ARLAS_WUI_URL=${ARLAS_WUI_URL:-/wui/}
    expose:
      - "80"
    networks:
      - arlas-net
