services:
  arlas-fam-wui: # ARLAS FAM is the ARLAS File and Archive Management interface. It allows exploration and registration of archives found in a directory.
    extends:
      file: ref-dc-logger.yaml
      service: log-rotated
    image: ${ARLAS_VERSION_FAM_WUI}
    platform: linux/x86_64
    container_name: fam-wui
    restart: always
    depends_on:
      arlas-server:
        condition: service_healthy
      fam-service:
        condition: service_healthy
    environment:
      - FAM_WUI_BASE_HREF=/fam-wui
      - ARLAS_AUTHENT_CLEAR_HASH=${ARLAS_AUTHENT_CLEAR_HASH:-true}
      - ARLAS_AUTHENT_CLIENT_ID=${ARLAS_AUTHENT_CLIENT_ID:-}
      - ARLAS_AUTHENT_DISABLE_AT_HASH_CHECK=${ARLAS_AUTHENT_DISABLE_AT_HASH_CHECK:-true}
      - ARLAS_AUTHENT_ENABLE_SESSION_CHECKS=${ARLAS_AUTHENT_ENABLE_SESSION_CHECKS:-true}
      - ARLAS_AUTHENT_FORCE_CONNECT=true
      - ARLAS_AUTHENT_ISSUER=${ARLAS_AUTHENT_ISSUER}
      - ARLAS_AUTHENT_LOGOUT_URL=${ARLAS_AUTHENT_LOGOUT_URL}
      - ARLAS_AUTHENT_MODE=${ARLAS_AUTHENT_MODE}
      - ARLAS_AUTHENT_REDIRECT_URI=https://${ARLAS_HOST}:443/fam-wui/callback
      - ARLAS_AUTHENT_REQUIRE_HTTPS=${ARLAS_AUTHENT_REQUIRE_HTTPS:-false}
      - ARLAS_AUTHENT_RESPONSE_TYPE=${ARLAS_AUTHENT_RESPONSE_TYPE}
      - ARLAS_AUTHENT_SCOPE=${ARLAS_AUTHENT_SCOPE}
      - ARLAS_AUTHENT_SHOW_DEBUG=${ARLAS_AUTHENT_SHOW_DEBUG:-false}
      - ARLAS_AUTHENT_SILENT_REFRESH_REDIRECT_URI=/fam-wui/silent-refresh.html
      - ARLAS_AUTHENT_SILENT_REFRESH_TIMEOUT=${ARLAS_AUTHENT_SILENT_REFRESH_TIMEOUT:-10000}
      - ARLAS_AUTHENT_STORAGE=${ARLAS_AUTHENT_STORAGE:-memorystorage}
      - ARLAS_AUTHENT_THRESHOLD=${ARLAS_AUTHENT_THRESHOLD}
      - ARLAS_AUTHENT_TIMEOUT_FACTOR=${ARLAS_AUTHENT_TIMEOUT_FACTOR:-0.75}
      - ARLAS_AUTHENT_USE_DISCOVERY=${ARLAS_AUTHENT_USE_DISCOVERY}
      - ARLAS_USE_AUTHENT=true
      - ARLAS_IAM_SERVER_URL=https://${ARLAS_HOST}/arlas_iam_server
      - ARLAS_TAB_NAME="ARLAS FAM Wui"
      - FAM_SERVER_URL=https://${ARLAS_HOST}/fam
      - FAM_DEFAULT_PATH=''
      - FAM_COLLECTION=${AIRS_COLLECTION}
      - FAM_ARCHIVES_PAGES_SIZE=${FAM_ARCHIVES_PAGES_SIZE}
      - FAM_FILES_PAGES_SIZE=${FAM_FILES_PAGES_SIZE}
      - APROC_SERVER_URL=https://${ARLAS_HOST}/aproc
      - APROC_COLLECTION=${AIRS_COLLECTION}
      - APROC_CATALOG=${AIAS_CATALOG_NAME}
      - AIRS_SERVER_URL=https://${ARLAS_HOST}/airs
      - AIRS_COLLECTION=${AIRS_COLLECTION}
      - 'ARLAS_STATIC_LINKS=${ARLAS_FAM_LINKS}'
    expose:
      - "8080"
    networks:
      - arlas-net
