services:
  titiler: # Titiler generates tiles for COG files
    image: ${TITILER_VERSION}
    container_name: 'titiler'
    restart: ${TITILER_RESTART_STRATEGY:-always}
    environment:
      - PORT=8000
      - TITILER_API_CORS_ORIGIN=*
      - WORKERS_PER_CORE=1
    expose:
      - "8000"
    networks:
      - arlas-net
