services:
  init-arlas-persistence-server-volume:
    image: alpine
    command: sh -c "chown -R 65532:65532 /data && tail -f /dev/null"
    volumes:
      - ${ARLAS_PERSISTENCE_STORAGE}:/data

  arlas-persistence-server: # ARLAS Persistence is a service for storing and retrieving small ojects, such as JSON documents or image previews.
    image: ${ARLAS_PERSISTENCE_VERSION}
    user: 65532:65532
    depends_on:
      - init-arlas-persistence-server-volume
    platform: linux/x86_64
    container_name: arlas-persistence-server
    restart: ${ARLAS_PERSISTENCE_RESTART_STRATEGY:-always}
    environment:
      - ARLAS_AUTH_POLICY_CLASS="${ARLAS_AUTH_POLICY_CLASS:-io.arlas.filter.impl.NoPolicyEnforcer}"
      - ARLAS_AUTH_PUBLIC_URIS=${ARLAS_AUTH_PUBLIC_URIS}
      - ARLAS_AUTH_PERMISSION_URL="${ARLAS_AUTH_PERMISSION_URL}"
      - ARLAS_AUTH_ENABLED=${ARLAS_AUTH_ENABLED:-false}
      - ARLAS_CACHE_TIMEOUT=${ARLAS_CACHE_TIMEOUT:-5}
      - ARLAS_PERSISTENCE_APP_PATH=${ARLAS_PERSISTENCE_APP_PATH:-/}
      - ARLAS_PERSISTENCE_ENGINE=${ARLAS_PERSISTENCE_ENGINE:-hibernate}
      - ARLAS_PERSISTENCE_HIBERNATE_PASSWORD=${POSTGRES_PASSWORD}
      - ARLAS_PERSISTENCE_HIBERNATE_URL=${ARLAS_PERSISTENCE_HIBERNATE_URL:-jdbc:postgresql://db:5432/arlas}
      - ARLAS_PERSISTENCE_HIBERNATE_USER=${POSTGRES_USER}
      - ARLAS_PERSISTENCE_LOCAL_FOLDER=/persist/
      - ARLAS_PERSISTENCE_LOGGING_CONSOLE_LEVEL=${ARLAS_PERSISTENCE_LOGGING_CONSOLE_LEVEL}
      - ARLAS_PERSISTENCE_LOGGING_LEVEL=${ARLAS_PERSISTENCE_LOGGING_LEVEL}
      - ARLAS_PERSISTENCE_PORT=${ARLAS_PERSISTENCE_PORT:-9997}
      - ARLAS_PERSISTENCE_PREFIX=${ARLAS_PERSISTENCE_PREFIX:-/arlas-persistence-server}
      - ELASTIC_APM_APPLICATION_PACKAGES=io.arlas
      - ELASTIC_APM_ENVIRONMENT=${ELASTIC_APM_ENVIRONMENT}
      - ELASTIC_APM_LOG_ECS_FORMATTER_ALLOW_LIST=${ELASTIC_APM_LOG_ECS_FORMATTER_ALLOW_LIST:-*}
      - ELASTIC_APM_LOG_ECS_REFORMATTING=${ELASTIC_APM_LOG_ECS_REFORMATTING:-OVERRIDE}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN}
      - ELASTIC_APM_SERVER_URLS=${ELASTIC_APM_SERVER_URLS:-http://apm-server:8200}
      - ELASTIC_APM_SERVICE_NAME=arlas-persistence-server
      - ELASTIC_APM_TRANSACTION_IGNORE_USER_AGENTS=GoogleHC/*, kube-probe/*, curl*, GoogleStackdriverMonitoring*
      - ELASTIC_APM_USE_JAXRS_PATH_AS_TRANSACTION_NAME=${ELASTIC_APM_USE_JAXRS_PATH_AS_TRANSACTION_NAME:-true}
      - JDK_JAVA_OPTIONS=${ARLAS_PERSISTENCE_JDK_JAVA_OPTIONS}
      - ARLAS_AUTH_KEYCLOAK_REALM=${ARLAS_AUTH_KEYCLOAK_REALM:-}
      - ARLAS_AUTH_KEYCLOAK_RESOURCE=${ARLAS_AUTH_KEYCLOAK_RESOURCE:-}
      - ARLAS_AUTH_KEYCLOAK_SECRET=${ARLAS_AUTH_KEYCLOAK_SECRET:-}
      - ARLAS_AUTH_KEYCLOAK_URL=${ARLAS_AUTH_KEYCLOAK_URL}
    volumes:
      - ${ARLAS_PERSISTENCE_STORAGE}:/persist/
      - ${PWD}/conf/arlas-ks.jks:/opt/app/arlas-ks.jks
    expose:
      - "9997"
    networks:
      - arlas-net
    extra_hosts:
      - ${ARLAS_HOST}:host-gateway
    logging:
      driver: "${DOCKER_LOGGING_DRIVER:-json-file}"
      options:
        tag: ${ARLAS_LOGGING_TAG:-arlas_logging}
    healthcheck:
      test: ["CMD","java","HttpHealthcheck","http://localhost:9997/admin/healthcheck"]
      interval: 20s
      timeout: 20s
      retries: 20
