services:
  apisix: # APISIX is ARLAS Stack gateway. It handles all the incoming trafic.
    image: ${APISIX_VERSION}
    platform: linux/x86_64
    container_name: apisix
    restart: ${APISIX_RESTART_STRATEGY:-always}
    environment:
      - APISIX_STAND_ALONE=${APISIX_STAND_ALONE:-true}
    ports:  
      - "80:9080" # !EXPOSE!
    volumes:
      - ${PWD}/conf/apisix/config.yaml:/usr/local/apisix/conf/config.yaml
      - ${PWD}/conf/apisix/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
    networks:
      - arlas-net 
    logging:
      driver: "${DOCKER_LOGGING_DRIVER:-json-file}"
      options:
        tag: ${ARLAS_LOGGING_TAG:-arlas_logging}
    extra_hosts:
      - ${ARLAS_HOST}:host-gateway
    healthcheck:
      test:
        - "CMD-SHELL"
        - "bash -c 'exec 3<>/dev/tcp/127.0.0.1/9090 && echo -e \"GET /v1/healthcheck HTTP/1.1\\r\\nHost: 127.0.0.1\\r\\nConnection: close\\r\\n\\r\\n\" >&3 && cat <&3 | grep -q \"200 OK\"' || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
