services:
  metricbeat:
    image: ${METRICBEAT_VERSION}
    container_name: metricbeat
    depends_on:
      elasticsearch-logs:
        condition: service_healthy
      kibana-logs:
        condition: service_healthy
    restart: ${ELASTIC_RESTART_STRATEGY:-always}
    command:
      -strict.perms=false
    user: root
    environment:
      - CA_CERT=certs/ca/ca.crt
      - ELASTIC_HOSTS_OUTPUT=https://elasticsearch-logs:9200
      - ELASTIC_HOSTS=https://elasticsearch:9200
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_USER=elastic
      - ES_CERT=certs/elasticsearch-logs/elasticsearch-logs.crt
      - ES_KEY=certs/elasticsearch-logs/elasticsearch-logs.key
    networks:
      - arlas-net
    volumes:
      - ${METRICBEAT_STORAGE_DIRECTORY:-/tmp/elastic/data}:/usr/share/metricbeat/data
      - ${ELASTIC_CERTS_DIRECTORY:-/tmp/elastic/certs}:/usr/share/metricbeat/certs
      - ${METRICBEAT_CONF_DIRECTORY:-/tmp/metricbeat/config}/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
