services:
  keycloak:
    image: ${KEYCLOAK_VERSION}
    platform: linux/x86_64
    container_name: keycloak
    command: [
      "start-dev",
      "--https-port=9443",
      "--https-key-store-file=/opt/keycloak/conf/keycloak.jks",
      "--https-key-store-password=arlaspassword",
      "--https-certificate-file=/opt/keycloak/conf/server.crt",
      "--https-certificate-key-file=/opt/keycloak/conf/server.key",
      "--import-realm",
      "--http-relative-path",
      "/auth"
    ]
    restart: ${ARLAS_KEYCLOAK_RESTART_STRATEGY:-always}
    environment:
      - KC_HEALTH_ENABLED=true # This is to enable kubernetes healthchecks
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_LOGIN}
      - KC_HTTPS_KEYSTORE_PATH=/opt/keycloak/conf/keycloak.jks
      - KC_HTTPS_KEYSTORE_PASSWORD=arlaspassword
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
    ports:
      - "9443:9443" # !EXPOSE!
    volumes:
      - ${KEYCLOAK_CONF_DIRECTORY}/keycloak.realm.json:/opt/keycloak/data/import/realm.json:ro
      - ${PWD}/conf/arlas-ks.jks:/opt/keycloak/conf/keycloak.jks:ro
      - ${PWD}/conf/server-ks.crt:/opt/keycloak/conf/server.crt:ro
      - ${PWD}/conf/server-ks.key:/opt/keycloak/conf/server.key:ro
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/localhost/8080"]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 40s
    networks:
      - arlas-net
    logging:
      driver: "${DOCKER_LOGGING_DRIVER:-json-file}"
      options:
        tag: ${ARLAS_LOGGING_TAG:-arlas_logging}
