services:
  pgadmin:
    image: ${PGADMIN4_VERSION}
    container_name: pgadmin
    depends_on:
      db:
        condition: service_healthy
    restart: ${PGADMIN_RESTART_STRATEGY:-always}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGA_LOGIN}
      - PGADMIN_DEFAULT_PASSWORD=${PGA_PASSWORD}
      - PGADMIN_ENABLE_TLS=${PGADMIN_ENABLE_TLS:-true}
      - PGADMIN_LISTEN_PORT=443
    ports:
      - "8443:443"
    networks:
      - arlas-net
    volumes:
      - ${PGADMIN_DATA_DIR}:/var/lib/pgadmin
    # TODO : can we set :ro on the certs:
      - ${PGADMIN_CERTS_DIRECTORY:-/tmp/pgadmin/certs}/server.cert:/certs/server.cert
      - ${PGADMIN_CERTS_DIRECTORY:-/tmp/pgadmin/certs}/server.key:/certs/server.key
      - ${PGADMIN_CONF_DIRECTORY:-/tmp/pgadmin/certs}:/pgadmin4
