services:
  arlas-builder:
    image: ${ARLAS_BUILDER_VERSION}
    container_name: arlas-builder
    depends_on:
      arlas-persistence-server:
        condition: service_healthy
    restart: ${ARLAS_BUILDER_RESTART_STRATEGY:-always}
    environment:
      - ARLAS_AUTHENT_CLEAR_HASH=${ARLAS_AUTHENT_CLEAR_HASH:-true}
      - ARLAS_AUTHENT_CLIENT_ID=${ARLAS_AUTHENT_CLIENT_ID:-}
      - ARLAS_AUTHENT_DISABLE_AT_HASH_CHECK=${ARLAS_AUTHENT_DISABLE_AT_HASH_CHECK:-true}
      - ARLAS_AUTHENT_ENABLE_SESSION_CHECKS=${ARLAS_AUTHENT_ENABLE_SESSION_CHECKS:-true}
      - ARLAS_AUTHENT_FORCE_CONNECT=${ARLAS_AUTHENT_FORCE_CONNECT}
      - ARLAS_AUTHENT_ISSUER=${ARLAS_AUTHENT_ISSUER}
      - ARLAS_AUTHENT_LOGIN_URL=${ARLAS_AUTHENT_LOGIN_URL}
      - ARLAS_AUTHENT_LOGOUT_URL=${ARLAS_AUTHENT_LOGOUT_URL}
      - ARLAS_AUTHENT_MODE=${ARLAS_AUTHENT_MODE}
      - ARLAS_AUTHENT_POST_LOGOUT_REDIRECT_URI=${ARLAS_AUTHENT_POST_LOGOUT_REDIRECT_URI}
      - ARLAS_AUTHENT_REDIRECT_URI=${ARLAS_AUTHENT_REDIRECT_URI:-/wui/callback}
      - ARLAS_AUTHENT_REQUIRE_HTTPS=${ARLAS_AUTHENT_REQUIRE_HTTPS:-false}
      - ARLAS_AUTHENT_RESPONSE_TYPE=${ARLAS_AUTHENT_RESPONSE_TYPE:-code}
      - ARLAS_AUTHENT_SCOPE=${ARLAS_AUTHENT_SCOPE:-profile}
      - ARLAS_AUTHENT_SHOW_DEBUG=${ARLAS_AUTHENT_SHOW_DEBUG:-false}
      - ARLAS_AUTHENT_SILENT_REFRESH_REDIRECT_URI=${ARLAS_AUTHENT_SILENT_REFRESH_REDIRECT_URI}
      - ARLAS_AUTHENT_SILENT_REFRESH_TIMEOUT=${ARLAS_AUTHENT_SILENT_REFRESH_TIMEOUT:-10000}
      - ARLAS_AUTHENT_STORAGE=${ARLAS_AUTHENT_STORAGE:-memorystorage}
      - ARLAS_AUTHENT_THRESHOLD=${ARLAS_AUTHENT_THRESHOLD}
      - ARLAS_AUTHENT_TIMEOUT_FACTOR=${ARLAS_AUTHENT_TIMEOUT_FACTOR:-0.75}
      - ARLAS_AUTHENT_USE_DISCOVERY=${ARLAS_AUTHENT_USE_DISCOVERY}
      - ARLAS_BASEMAPS=${ARLAS_BASEMAPS:-[{"name":"Empty","url":"/styles/empty/style.json","image":null}]}
      - ARLAS_BASEMAPS=[{"name":"Streets-light","url":"https://api.maptiler.com/maps/208a41eb-368f-4003-8e3c-2dba0d90b3cb/style.json?key=xIhbu1RwgdbxfZNmoXn4","image":"https://api.maptiler.com/maps/208a41eb-368f-4003-8e3c-2dba0d90b3cb/0/0/0.png?key=xIhbu1RwgdbxfZNmoXn4"}]
      - ARLAS_BUILDER_BASE_HREF=${ARLAS_BUILDER_BASE_HREF:-/builder}
      - ARLAS_EXTERNAL_NODE_PAGE=${ARLAS_EXTERNAL_NODE_PAGE:-true}
      - ARLAS_IAM_SERVER_URL=${ARLAS_IAM_SERVER_URL:-/arlas_iam_server}
      - ARLAS_PERMISSIONS_URL=${ARLAS_PERMISSIONS_URL:-/arlas_permissions_server}
      - ARLAS_PERSISTENCE_URL=${ARLAS_PERSISTENCE_URL:-/arlas_persistence_server}
      - ARLAS_SERVER_URL=${ARLAS_SERVER_URL:-/arlas}
      - ARLAS_USE_AUTHENT=${ARLAS_USE_AUTHENT}
      - ARLAS_WUI_URL=${ARLAS_WUI_URL:-/wui/}
    expose:
      - "80"
    networks:
      - arlas-net
