apiVersion: v2
name: arlas-aias
description: A Helm Chart to deploy the ARLAS Exploration Stack with AIAS services
version: 27.63.0
appVersion: 27.63.0
dependencies:
  # ARLAS BACKEND DEPENDENCIES
  - name: arlas-services
    version: 27.63.0
    repository: "file://../arlas-services"
    condition: deployment.arlas.services.enabled
  - name: aias-services
    version: 27.63.0
    repository: "file://../aias-services"
    condition: deployment.aias.enabled
  # ARLAS FRONTEND DEPENDENCIES
  - name: arlas-uis
    version: 27.63.0
    repository: "file://../arlas-uis"
    condition: deployment.arlas.uis.enabled
  # THIRD PARTY LOCAL DEPENDENCIES
  - name: titiler
    repository: "file://../titiler"
    version: 27.63.0
    condition: deployment.titiler.enabled
  # THIRD PARTY REMOTE DEPENDENCIES
  - name: elasticsearch
    repository: https://charts.bitnami.com/bitnami
    version: 22.0.4
    condition: deployment.elasticsearch.enabled
  - name: minio
    repository: https://charts.bitnami.com/bitnami
    version: 14.10.5
    condition: deployment.minio.enabled
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 16.0.11
    condition: deployment.rabbitmq.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 21.2.13
    condition: deployment.redis.enabled
  - name: keycloak
    repository: https://charts.bitnami.com/bitnami
    version: 20.0.1
    condition: deployment.keycloak.enabled
