global: 
  # -- DNS domain hosting ARLAS
  # -- __MUST BE CONFIGURED:__ The domain name for accessing the ARLAS deployment
  dnsDomain: &arlasAppDnsDomain site.arlas.k8s
  # -- __MUST BE CONFIGURED:__ The protocol for accessing the ARLAS deployment
  protocol: &arlasAppProtocol http
  # -- __MUST BE CONFIGURED:__ The default ARLAS storage class for the persistence. By default, the `standard-retain` storage class is created based on the provisioner `rancher.io/local-path` with a retain policy.
  defaultStorageClass: &arlasAppDefaultStorageClass standard-retain

  keycloak:
    # -- __MUST BE CONFIGURED:__ The secret configured for the ARLAS client of the keyckloak's realm 
    secret: &arlasAppKeycloakSecret rha14c4202RB0Dxlke6ZNCCTw9gkvLJ8
    # -- __MUST BE CONFIGURED:__ Keycloak URL
    url: &arlasAppKeycloakUrl http://keycloak.arlas.k8s:8080/auth

  # -- __MUST BE CONFIGURED:__ The issuer's uri
  authIssuer: &arlasAppAuthIssuer http://keycloak.arlas.k8s:8080/auth/realms/arlas 
  # -- The logout URL to be used
  logoutUrl: &arlasAppLogoutUrl 

  # -- __MUST BE CONFIGURED:__ Name of the organization using AIAS
  organization: &arlasAppOrganization org.com

  # -- Elasticsearch login for elasticsearch itself and the services that are connecting to elasticsearch
  elasticLogin: &arlasAppElasticLogin elastic
  # -- __MUST BE CONFIGURED:__ Elasticsearch password for elasticsearch itself and the services that are connecting to elasticsearch
  elasticPassword: &arlasAppElasticPassword secret4elastic

  # -- Minio login for minio itself and the services that are connecting to minio
  minioLogin: &arlasAppMinioLogin minioadmin
  # -- __MUST BE CONFIGURED:__ Minio password for minio itself and the services that are connecting to minio
  minioPassword: &arlasAppMinioPassword secret4minio

  # -- Keycloak admin login for keycloak deployment (for test only)
  keycloakLogin: &arlasAppKeycloakLogin admin
  # -- __MUST BE CONFIGURED:__ Keycloak admin password 
  keycloakPassword: &arlasAppKeycloakPassword secret4keycloak

  # -- RabbitMQ Login
  rabbitMQLogin: &arlasAppRabbitMQLogin admin
  
  # -- __MUST BE CONFIGURED:__ RabbitMQ Password
  rabbitMQPassword: &arlasAppRabbitMQPassword secret4rabbitmq

  # -- __MUST BE CONFIGURED:__ redis Password
  redisPassword: &arlasAppRedisPassword secret4redis

  postgresql:
    auth:
      # -- __MUST BE CONFIGURED:__ postgres password for keycloak
      password: secret4postgres

deployment: 
  elasticsearch:
    # -- Should the chart deploy elasticsearch
    enabled: true
  minio:
    # -- Should the chart deploy minio
    enabled: true
  apisix:
    # -- Should the chart deploy apisix
    enabled: true
  rabbitmq:
    # -- Should the chart deploy rabbitmq
    enabled: true
  redis:
    # -- Should the chart deploy redis
    enabled: true
  keycloak: 
    # -- __MUST BE CONFIGURED:__ Should the chart deploy keycloak. __Enable for tests only__ or configure carefully the chart for your production needs.
    enabled: true
  titiler:
    # -- Should the chart deploy titiler
    enabled: true


# ARLAS SERVICES
# @ignored
arlas-services:
  dnsDomain: *arlasAppDnsDomain
  protocol: *arlasAppProtocol
  defaultStorageClass: *arlasAppDefaultStorageClass
  elastic:
    login: *arlasAppElasticLogin
    password: *arlasAppElasticPassword
  logger:
    # -- Logging level
    loggingLevel: DEBUG
    # -- Console logging level
    loggingConsoleLevel: DEBUG
  keycloak:
    secret: *arlasAppKeycloakSecret
    url: *arlasAppKeycloakUrl

# ARLAS WUI
# @ignored
arlas-uis:
  dnsDomain: *arlasAppDnsDomain
  protocol: *arlasAppProtocol
  defaultStorageClass: *arlasAppDefaultStorageClass
  authent:
    issuer: *arlasAppAuthIssuer
    logoutUrl: *arlasAppLogoutUrl
  logger:
    # -- Logging level
    loggingLevel: INFO
    # -- Console logging level
    loggingConsoleLevel: INFO
  # -- __MUST BE CONFIGURED:__ Set to 120 Gi if you copy the full basemap
  basemap:
    storageSize: 50Mi

# AIAS SERVICES
# @ignored
aias-services:
  dnsDomain: *arlasAppDnsDomain
  protocol: *arlasAppProtocol
  s3:
    accessKeyId: *arlasAppMinioLogin
    secret: *arlasAppMinioPassword
  elastic:
    login: *arlasAppElasticLogin
    password: *arlasAppElasticPassword
  logger:
    # -- Logging level
    loggingLevel: INFO
    # -- Console logging level
    loggingConsoleLevel: INFO
  organisation: *arlasAppOrganization

  # @ignored
  rabbitmq: 
    login: *arlasAppRabbitMQLogin
    password: *arlasAppRabbitMQPassword
  # @ignored

  redis:
    password: *arlasAppRedisPassword

  services:
    aproc:
      worker:
        replicaCount: 1
        resources:
          limits:
            cpu: 2
            memory: 10Gi
        nodeSelector: {}
        tolerations: []
        affinity: {}

# ELASTICSEARCH
# @ignored
elasticsearch:
  global:
    defaultStorageClass: *arlasAppDefaultStorageClass
  service:
    type: LoadBalancer
  master:
    masterOnly: false
    replicaCount: 1
    persistentVolumeClaimRetentionPolicy:
      enabled: true
  data:
    replicaCount: 0 # 0 for a single node cluster
    persistentVolumeClaimRetentionPolicy:
      enabled: true
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
  security:
    enabled: true
    elasticPassword: *arlasAppElasticPassword
    tls:
      # AutoGenerate TLS certs for elastic
      autoGenerated: true

# RABBITMQ
# @ignored
rabbitmq:
  global:
    defaultStorageClass: *arlasAppDefaultStorageClass
  resources:
    limits:
      memory: 300Mi
  auth:
    username: *arlasAppRabbitMQLogin
    password: *arlasAppRabbitMQPassword
  persistence:
    storageClass: *arlasAppDefaultStorageClass
  persistentVolumeClaimRetentionPolicy:
    enabled: true

# REDIS
# @ignored
redis:
  global:
    defaultStorageClass: *arlasAppDefaultStorageClass
  architecture: standalone
  auth:
    password: *arlasAppRedisPassword
  commonConfiguration: |
    loadmodule /opt/bitnami/redis/lib/redis/modules/redisbloom.so
    loadmodule /opt/bitnami/redis/lib/redis/modules/redisearch.so
    loadmodule /opt/bitnami/redis/lib/redis/modules/rejson.so
    loadmodule /opt/bitnami/redis/lib/redis/modules/redistimeseries.so
  persistence:
    storageClass: *arlasAppDefaultStorageClass
  master:
    persistentVolumeClaimRetentionPolicy:
      enabled: true
  replica:
    persistentVolumeClaimRetentionPolicy:
      enabled: true

# MINIO
# @ignored
minio:
  global:
    defaultStorageClass: *arlasAppDefaultStorageClass
  auth:
    rootUser: *arlasAppMinioLogin
    rootPassword: *arlasAppMinioPassword  

# KEYCLOAK
# @ignored  
keycloak:
  global:
    defaultStorageClass: *arlasAppDefaultStorageClass

  # Add extra volumes and volume mounts for realm import
  extraVolumes:
    - name: realm-config
      configMap:
        name: keycloak-realm-configmap

  extraVolumeMounts:
    - name: realm-config
      mountPath: /opt/bitnami/keycloak/data/import
      
  # Enable realm import at startup
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"

  httpRelativePath: /auth/
  resourcesPreset: medium
  readinessProbe:
    initialDelaySeconds: 300
    timeoutSeconds: 60
  startupProbe:
    initialDelaySeconds: 300
    timeoutSeconds: 60
  auth:
    adminUser: *arlasAppKeycloakLogin
    adminPassword: *arlasAppKeycloakPassword
  service:
    type: LoadBalancer
    ports:
      http: 8080
      https: 8443

