apisix:
  global:
    security:
      allowInsecureImages: true
  image:
    repository: bitnamilegacy/apisix
  usePasswordFiles: false
  controlPlane:
    enabled: false
  ingressController:
    enabled: false
  etcd:
    enabled: false
  dashboard:
    enabled: false
  dataPlane:
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    extraConfig:
      deployment:
        role_data_plane:
          config_provider: yaml
    extraVolumes:
      - name: routes
        configMap:
          name: apisix-routes
      - name: apisix-logs
        emptyDir: {}

    extraVolumeMounts:
      - name: routes
        mountPath: /usr/local/apisix/conf/apisix.yaml
        subPath: apisix.yaml
      - name: apisix-logs
        mountPath: /usr/local/apisix/logs

  extraDeploy:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: apisix-routes
      data:
        apisix.yaml: |-
          routes:
            -
              uri: /wui/*
              upstream:
                nodes:
                  "arlas-wui:8080": 1
              plugins:
                proxy-rewrite:
                  regex_uri: ["/wui/(.*)", "/$1"]
            -
              uri: /arlas/*
              upstream:
                nodes:
                  "arlas-server:8000": 1
            -
              uri: /builder/*
              upstream:
                nodes:
                  "arlas-builder:8080": 1
              plugins:
                proxy-rewrite:
                  regex_uri: ["/builder/(.*)", "/$1"]
            -
              uri: /
              plugins:
                redirect:
                  uri: /hub/
            -
              uri: /hub/*
              upstream:
                nodes:
                  "arlas-hub:8080": 1
              plugins:
                proxy-rewrite:
                  regex_uri: ["/hub/(.*)", "/$1"]
            -
              uri: /permissions/*
              upstream:
                nodes:
                  "arlas-permissions-server:8000": 1
            -
              uri: /persist/*
              upstream:
                nodes:
                  "arlas-persistence-server:8000": 1
            -
              uri: /cog/preview*
              upstream:
                nodes:
                  "arlas-stack-titiler:8000": 1
              plugins:
                proxy-rewrite:
                  regex_uri: ["/(.*)", "/$1"]
                forward-auth:
                  uri: http://arlas-agate:8000/agate/authorization/cog_preview
                  request_headers: ["Authorization", "arlas-org-filter"]
                  keepalive: false
            -
              uri: /cog/statistics*
              upstream:
                nodes:
                  "arlas-stack-titiler:8000": 1
              plugins:
                proxy-rewrite:
                  regex_uri: ["/(.*)", "/$1"]
                forward-auth:
                  uri: http://arlas-agate:8000/agate/authorization/cog_statistics
                  request_headers: ["Authorization", "arlas-org-filter"]
                  keepalive: false
            -
              uri: /cog/*
              upstream:
                nodes:
                  "arlas-stack-titiler:8000": 1
              plugins:
                proxy-rewrite:
                  regex_uri: ["/(.*)", "/$1"]
                forward-auth:
                  uri: http://arlas-agate:8000/agate/authorization/cog
                  request_headers: ["Authorization", "arlas-org-filter"]
                  keepalive: false
            -
              uri: /colorMaps*
              upstream:
                nodes:
                  "arlas-stack-titiler:8000": 1
              plugins:
                proxy-rewrite:
                  regex_uri: ["/(.*)", "/$1"]
            -
              uri: /fam-wui
              plugins:
                redirect:
                  uri: /fam-wui/
            -
              uri: /fam-wui/*
              upstream:
                nodes:
                  "arlas-fam-wui:8080": 1
              plugins:
                proxy-rewrite:
                  regex_uri: ["/fam-wui/(.*)", "/$1"]
            -
              uri: /airs-storage/*
              methods: ["GET"]
              upstream:
                nodes:
                  "arlas-stack-minio:9000": 1
              plugins:
                forward-auth:
                  uri: http://arlas-agate:8000/agate/authorization/airs-storage
                  request_headers: ["Authorization", "arlas-org-filter"]
                  keepalive: false
            -
              uri: /fam/*
              upstream:
                nodes:
                  "arlas-fam:8000": 1
              plugins:
                forward-auth:
                  uri: http://arlas-agate:8000/agate/url-role-based-authorization
                  request_headers: ["Authorization", "arlas-org-filter"]
                  keepalive: false
            -
              uri: /fam/files
              upstream:
                nodes:
                  "arlas-fam:8000": 1
              plugins:
                forward-auth:
                  uri: http://arlas-agate:8000/agate/url-role-based-authorization
                  request_headers: ["Authorization", "arlas-org-filter"]
                  keepalive: false
            -
              uri: /airs/collections/*
              upstream:
                nodes:
                  "airs-server:8000": 1
              plugins:
                forward-auth:
                  uri: http://arlas-agate:8000/agate/url-role-based-authorization
                  request_headers: ["Authorization", "arlas-org-filter"]
                  keepalive: false
                proxy-control: 
                  request_buffering: false
            -
              uri: /aproc/processes/*
              upstream:
                nodes:
                  "aproc-service:8000": 1
              plugins:
                forward-auth:
                  uri: http://arlas-agate:8000/agate/url-role-based-authorization
                  request_headers: ["Authorization", "arlas-org-filter"]
                  keepalive: false
            -
              uri: /aproc/jobs
              upstream:
                nodes:
                  "aproc-service:8000": 1
              plugins:
                forward-auth:
                  uri: http://arlas-agate:8000/agate/url-role-based-authorization
                  request_headers: ["Authorization", "arlas-org-filter"]
                  keepalive: false
            -
              uri: /aproc/jobs/*
              upstream:
                nodes:
                  "aproc-service:8000": 1
              plugins:
                forward-auth:
                  uri: http://arlas-agate:8000/agate/url-role-based-authorization
                  request_headers: ["Authorization", "arlas-org-filter"]
                  keepalive: false
            -
              uri: /agate/healthcheck
              methods: ["GET"]
              upstream:
                nodes:
                  "arlas-agate:8000": 1
            -
              uri: /airs/healthcheck
              methods: ["GET"]
              upstream:
                nodes:
                  "airs-server:8000": 1
            -
              uri: /aproc/healthcheck
              methods: ["GET"]
              upstream:
                nodes:
                  "aproc-service:8000": 1
            -
              uri: /arlas/admin/healthcheck
              methods: ["GET"]
              upstream:
                nodes:
                  "arlas-server:8000": 1

          #END
