global: 
  # -- __MUST BE CONFIGURED:__ The domain name for accessing the ARLAS deployment
  dnsDomain: &arlasAppDnsDomain site.arlas.k8s

  # -- __MUST BE CONFIGURED:__ The domain name for accessing ES for ARLAS deployment
  elasticDnsDomain: &arlasAppElasticDnsDomain elastic.arlas.k8s

  # -- __MUST BE CONFIGURED:__ The domain name for accessing keycloak for ARLAS deployment
  keycloakDnsDomain: &arlasAppKeycloakDnsDomain keycloak.arlas.k8s

  # -- __MUST BE CONFIGURED:__ The protocol for accessing the ARLAS deployment
  protocol: &arlasAppProtocol https

  # -- __MUST BE CONFIGURED:__ The default ingress class. By default, the `nginx` controler is used.
  ingressClassName: &arlasAppIngressClassName nginx

  # -- __MUST BE CONFIGURED:__ The default ARLAS storage class for the persistence. By default, the `standard-retain` storage class is created based on the provisioner `rancher.io/local-path` with a retain policy.
  defaultStorageClass: &arlasAppDefaultStorageClass standard-retain

  keycloak:
    # -- __MUST BE CONFIGURED:__ The secret configured for the ARLAS client of the keyckloak's realm 
    secret: &arlasAppKeycloakSecret rha14c4202RB0Dxlke6ZNCCTw9gkvLJ8
    # -- __MUST BE CONFIGURED:__ Keycloak URL
    url: &arlasAppKeycloakUrl https://keycloak.arlas.k8s/auth

  # -- __MUST BE CONFIGURED:__ The issuer's uri
  authIssuer: &arlasAppAuthIssuer https://keycloak.arlas.k8s/auth/realms/arlas 
  # -- The logout URL to be used
  logoutUrl: &arlasAppLogoutUrl 

  # -- __MUST BE CONFIGURED:__ Name of the organization using AIAS
  organization: &arlasAppOrganization org.com

  # -- Elasticsearch login for elasticsearch itself and the services that are connecting to elasticsearch
  elasticLogin: &arlasAppElasticLogin elastic
  # -- __MUST BE CONFIGURED:__ Elasticsearch password for elasticsearch itself and the services that are connecting to elasticsearch
  elasticPassword: &arlasAppElasticPassword secret4elastic

  # -- Minio login for minio itself and the services that are connecting to minio
  minioLogin: &arlasAppMinioLogin minioadmin
  # -- __MUST BE CONFIGURED:__ Minio password for minio itself and the services that are connecting to minio
  minioPassword: &arlasAppMinioPassword secret4minio

  # -- Keycloak admin login for keycloak deployment (for test only)
  keycloakLogin: &arlasAppKeycloakLogin admin
  # -- __MUST BE CONFIGURED:__ Keycloak admin password 
  keycloakPassword: &arlasAppKeycloakPassword secret4keycloak

  # -- RabbitMQ Login
  rabbitMQLogin: &arlasAppRabbitMQLogin admin
  
  # -- __MUST BE CONFIGURED:__ RabbitMQ Password
  rabbitMQPassword: &arlasAppRabbitMQPassword secret4rabbitmq

  # -- __MUST BE CONFIGURED:__ redis Password
  redisPassword: &arlasAppRedisPassword secret4redis

  postgresql:
    auth:
      # -- __MUST BE CONFIGURED:__ postgres password for keycloak
      password: secret4postgres

deployment: 
  elasticsearch:
    # -- Should the chart deploy elasticsearch
    enabled: true
  minio:
    # -- Should the chart deploy minio
    enabled: true
  apisix:
    # -- Should the chart deploy apisix
    enabled: true
  rabbitmq:
    # -- Should the chart deploy rabbitmq
    enabled: true
  redis:
    # -- Should the chart deploy redis
    enabled: true
  keycloak: 
    # -- __MUST BE CONFIGURED:__ Should the chart deploy keycloak. __Enable for tests only__ or configure carefully the chart for your production needs.
    enabled: true
  titiler:
    # -- Should the chart deploy titiler
    enabled: true


# ARLAS SERVICES
arlas-services:
  # @ignored  
  dnsDomain: *arlasAppDnsDomain
  # @ignored  
  protocol: *arlasAppProtocol
  # @ignored  
  defaultStorageClass: *arlasAppDefaultStorageClass
  # @ignored  
  elastic:
    login: *arlasAppElasticLogin
    password: *arlasAppElasticPassword
  logger:
    # -- Logging level
    loggingLevel: DEBUG
    # -- Console logging level
    loggingConsoleLevel: DEBUG
  # @ignored  
  keycloak:
    secret: *arlasAppKeycloakSecret
    url: *arlasAppKeycloakUrl
  services:
    # -- __MUST BE CONFIGURED:__ Set to true if you want the services to use the certificate contained in the k8s/charts/arlas-stack/templates/keycloak-certificate-configmap.yaml file and enable the keycloak.ingress.extraTls bloc. False otherwise and disable the keycloak.ingress.extraTls bloc.
    mountCertificate: true

# ARLAS WUI
arlas-uis:
  # @ignored  
  dnsDomain: *arlasAppDnsDomain
  # @ignored  
  protocol: *arlasAppProtocol
  # @ignored  
  defaultStorageClass: *arlasAppDefaultStorageClass
  # @ignored  
  authent:
    issuer: *arlasAppAuthIssuer
    logoutUrl: *arlasAppLogoutUrl
  logger:
    # -- Logging level
    loggingLevel: INFO
    # -- Console logging level
    loggingConsoleLevel: INFO
  # -- __MUST BE CONFIGURED:__ Set to 120 Gi if you copy the full basemap
  basemap:
    storageSize: 50Mi

# AIAS SERVICES
aias-services:
  # @ignored  
  dnsDomain: *arlasAppDnsDomain
  # @ignored  
  protocol: *arlasAppProtocol
  # @ignored  
  s3:
    accessKeyId: *arlasAppMinioLogin
    secret: *arlasAppMinioPassword
  # @ignored  
  elastic:
    login: *arlasAppElasticLogin
    password: *arlasAppElasticPassword
  logger:
    # -- Logging level
    loggingLevel: INFO
    # -- Console logging level
    loggingConsoleLevel: INFO
  # @ignored  
  organisation: *arlasAppOrganization

  # @ignored
  rabbitmq: 
    login: *arlasAppRabbitMQLogin
    password: *arlasAppRabbitMQPassword

  # @ignored
  redis:
    password: *arlasAppRedisPassword

  services:
    aproc:
      worker:
        replicaCount: 1
        resources:
          limits:
            cpu: 2
            memory: 10Gi
        nodeSelector: {}
        tolerations: []
        affinity: {}

# ELASTICSEARCH
elasticsearch:
  # @ignored  
  global:
    defaultStorageClass: *arlasAppDefaultStorageClass
  service:
    type: ClusterIP
  master:
    resourcesPreset: large
    masterOnly: false
    replicaCount: 1
    persistentVolumeClaimRetentionPolicy:
      enabled: true
  data:
    replicaCount: 0 # 0 for a single node cluster
    persistentVolumeClaimRetentionPolicy:
      enabled: true
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
  security:
    enabled: true
  # @ignored  
    elasticPassword: *arlasAppElasticPassword
    tls:
      # AutoGenerate TLS certs for elastic
      autoGenerated: true

# RABBITMQ
rabbitmq:
  # @ignored  
  global:
    defaultStorageClass: *arlasAppDefaultStorageClass
  resources:
    limits:
      memory: 2Gi
    requests:
      memory: 1Gi

  # @ignored  
  auth:
    username: *arlasAppRabbitMQLogin
    password: *arlasAppRabbitMQPassword
  # @ignored  
  persistence:
    storageClass: *arlasAppDefaultStorageClass
  persistentVolumeClaimRetentionPolicy:
    enabled: true

# REDIS
redis:
  # @ignored  
  global:
    defaultStorageClass: *arlasAppDefaultStorageClass
  architecture: standalone
  # @ignored  
  auth:
    password: *arlasAppRedisPassword
  commonConfiguration: |
    loadmodule /opt/bitnami/redis/lib/redis/modules/redisbloom.so
    loadmodule /opt/bitnami/redis/lib/redis/modules/redisearch.so
    loadmodule /opt/bitnami/redis/lib/redis/modules/rejson.so
    loadmodule /opt/bitnami/redis/lib/redis/modules/redistimeseries.so
  # @ignored  
  master:
    persistentVolumeClaimRetentionPolicy:
      enabled: true
    persistence:
      storageClass: *arlasAppDefaultStorageClass
  replica:
    persistentVolumeClaimRetentionPolicy:
      enabled: true
    persistence:
      storageClass: *arlasAppDefaultStorageClass

# MINIO
minio:
  # @ignored  
  global:
    defaultStorageClass: *arlasAppDefaultStorageClass
  persistence:
    storageClass: *arlasAppDefaultStorageClass
  # @ignored  
  auth:
    rootUser: *arlasAppMinioLogin
    rootPassword: *arlasAppMinioPassword  

# KEYCLOAK
keycloak:
  # @ignored  
  global:
    defaultStorageClass: *arlasAppDefaultStorageClass

  # Add extra volumes and volume mounts for realm import
  extraVolumes:
    - name: realm-config
      configMap:
        name: keycloak-realm-configmap

  extraVolumeMounts:
    - name: realm-config
      mountPath: /opt/bitnami/keycloak/data/import
      
  # Enable realm import at startup
  extraEnvVars:
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"

  httpRelativePath: /auth/
  resourcesPreset: medium
  readinessProbe:
    initialDelaySeconds: 300
    timeoutSeconds: 60
  startupProbe:
    initialDelaySeconds: 300
    timeoutSeconds: 60
  auth:
    adminUser: *arlasAppKeycloakLogin
    adminPassword: *arlasAppKeycloakPassword
  service:
    type: ClusterIP
    http:
      enabled: true
    ports:
      http: 8080
      https: 8443
  ingress:
  # @ignored  
    ingressClassName: *arlasAppIngressClassName 
    enabled: true
  # @ignored  
    hostname: *arlasAppKeycloakDnsDomain
    tls: true
    path: "/"
    servicePort: 8080
    annotations:
      # -- Default nginx ingress has default proxy buffers that are too small for keycloak headers.
      nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "8"

    # -- __MUST BE CONFIGURED:__ Enable extraTls bloc if you provide the certificate in the keycloak-tls secret, comment the block below otherwise. If the block is enabled, then set arlas-services.services.mountCertificate must be true, false otherwise (so that the certificate is mounted on the pods).
    # start-of-block   
    extraTls:
      - hosts: 
        - *arlasAppKeycloakDnsDomain
        secretName: keycloak-tls
    # end-of-block   
  proxy: edge
