{{- if and .Values.deployment.arlas.uis.gateway.enabled .Values.global.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: arlas-hub-route
spec:
  parentRefs:
    - name: {{ .Values.global.gateway.name }}
      sectionName: https
  hostnames:
    - {{ .Values.global.dnsDomain | quote }}
  rules:
    - matches:
        - path:
            type: Exact
            value: /hub
      filters:
        - type: RequestRedirect
          requestRedirect:
            statusCode: 301
            path:
              type: ReplaceFullPath
              replaceFullPath: /hub/
    - matches:
        - path:
            type: PathPrefix
            value: /hub/
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: {{ (get .Values "arlas-uis").uis.hub.serviceName }}
          port: {{ (get .Values "arlas-uis").uis.servicePort }}
{{- end }}
