{{- if and .Values.deployment.aias.services.fam.gateway.enabled .Values.global.gateway.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: fam-ext-auth
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: arlas-fam-route
  extAuth:
    headersToExtAuth:
      {{- toYaml .Values.global.gateway.extAuth.headersToExtAuth | nindent 6 }}
    http:
      backendRefs:
        - name: {{ (get .Values "aias-services").services.agate.serviceName }}
          port: {{ (get .Values "aias-services").services.servicePort }}
      pathOverride: /agate/url-role-based-authorization
      headersToBackend:
        {{- toYaml .Values.global.gateway.extAuth.headersToBackend | nindent 8 }}
{{- end }}