{{- if and .Values.deployment.aias.services.minio.gateway.enabled .Values.global.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: arlas-minio-route
spec:
  parentRefs:
    - name: {{ .Values.global.gateway.name }}
      sectionName: https
  hostnames:
    - {{ .Values.global.dnsDomain | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /airs-storage/
      backendRefs:
        - name: {{ .Values.deployment.aias.services.minio.serviceName }}
          port: {{ .Values.deployment.aias.services.minio.port }}
{{- end }}