apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  replicas: {{ int .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ .Values.serviceName }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.serviceName }}
          image: {{ .Values.image }}
          ports:
            - name: http
              containerPort: {{ .Values.servicePort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.famWuiURL }}
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.famWuiURL }}
              port: http
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            # AUTHENTICATION
            - name: ARLAS_USE_AUTHENT
              value: {{ .Values.authent.useAuthent | quote }}
            - name: ARLAS_AUTHENT_MODE
              value: {{ .Values.authent.authMode | quote  }}
            - name: ARLAS_AUTHENT_FORCE_CONNECT
              value: {{ .Values.authent.forceConnect | quote  }}
            - name: ARLAS_AUTHENT_USE_DISCOVERY
              value: {{ .Values.authent.useDiscovery  | quote }}
            - name: ARLAS_AUTHENT_ISSUER
              value: {{ .Values.authent.issuer }}
            - name: ARLAS_AUTHENT_CLIENT_ID
              value: {{ .Values.authent.clientId }}
            - name: ARLAS_AUTHENT_REDIRECT_URI
              value: https://{{ .Values.dnsDomain }}{{ .Values.famWuiURL }}/callback
            - name: ARLAS_AUTHENT_SILENT_REFRESH_REDIRECT_URI
              value: https://{{ .Values.dnsDomain }}{{ .Values.famWuiURL }}/silent-refresh.html
            - name: ARLAS_AUTHENT_SCOPE
              value: {{ .Values.authent.scope }}
            - name: ARLAS_AUTHENT_CUSTOM_QUERY_PARAMS
              value: {{ .Values.authent.customQueryParams | toPrettyJson | quote }}
            - name: ARLAS_AUTHENT_REQUIRE_HTTPS
              value: {{ .Values.authent.requireHttps | quote  }}
            - name: ARLAS_AUTHENT_RESPONSE_TYPE
              value: {{ .Values.authent.responseType }}
            - name: ARLAS_AUTHENT_SILENT_REFRESH_TIMEOUT
              value: {{ .Values.authent.silentRefreshTimeout | quote }}
            - name: ARLAS_AUTHENT_TIMEOUT_FACTOR
              value: {{ .Values.authent.timeoutFactor | quote }}
            - name: ARLAS_AUTHENT_ENABLE_SESSION_CHECKS
              value: {{ .Values.authent.sessionChecksEnabled | quote }}
            - name: ARLAS_AUTHENT_CLEAR_HASH
              value: {{ .Values.authent.clearHashAfterLogin | quote }}
            - name: ARLAS_AUTHENT_DISABLE_AT_HASH_CHECK
              value: {{ .Values.authent.disableAtHashCheck | quote }}
            - name: ARLAS_AUTHENT_SHOW_DEBUG
              value: {{ .Values.authent.showDebugInformation | quote }}
            - name: ARLAS_AUTHENT_STORAGE
              value: {{ .Values.authent.storage | quote }}
            - name: ARLAS_AUTHENT_LOGOUT_URL
              value: {{ .Values.authent.logoutUrl | quote }}

            # UI LINKS
            - name: FAM_WUI_BASE_HREF
              value: {{ .Values.famWuiURL | quote }}
            - name: ARLAS_BUILDER_URL
              value: {{ .Values.builderURL | quote }}
            - name: ARLAS_HUB_BASE_HREF
              value: {{ .Values.hubURL | quote }}
            - name: ARLAS_WUI_URL
              value: {{ .Values.wuiURL | quote }}
            - name: ARLAS_HUB_APP_PATH
              value: ""

            # USER INTERFACE CONFIGURATION
            - name: ARLAS_STATIC_LINKS
              value: {{ .Values.links | toPrettyJson | quote }}
            - name: ARLAS_TAB_NAME
              value: {{ .Values.tabName | quote }}
            - name: FAM_SERVER_URL
              value: https://{{ .Values.dnsDomain }}/{{ .Values.famWuiURL }}
            - name: FAM_DEFAULT_PATH
              value: {{ .Values.famDefaultURL | quote }}
            - name: FAM_COLLECTION
              value: {{ .Values.collectionName | quote }}
            - name: FAM_ARCHIVES_PAGES_SIZE
              value: {{ .Values.archivePageSize | quote }}
            - name: FAM_FILES_PAGES_SIZE
              value: {{ .Values.filePageSize | quote }}
            - name: APROC_CATALOG
              value: {{ .Values.catalog | quote }}
            - name: AIRS_COLLECTION
              value: {{ .Values.collectionName | quote }}


            # SERVICES
            - name: APROC_SERVER_URL
              value: https://{{ .Values.dnsDomain }}{{ .Values.aprocURL }}
            - name: AIRS_SERVER_URL
              value: https://{{ .Values.dnsDomain }}{{ .Values.airsURL }}

          {{- range $configurationName, $configurationInfo := .Values.configuration }}
            - name: {{ (index $.Values.configuration $configurationName).environmentVariable }}
              value: file://{{ (index $.Values.configuration $configurationName).mountPath }}
          {{- end }}

      # NODE SELECTION      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}