{{- if .Values.deployment.elasticsearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.elasticsearch.clusterName | default "arlas-elasticsearch" }}-user
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.elasticsearch.user.login }}
  password: {{ .Values.elasticsearch.user.password }}
  roles: superuser
{{- end }}