{{- range $key, $inst := (include "elastic.instances" . | fromJson) }}
{{- if $inst.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $inst.elasticsearch.clusterName }}-user
type: kubernetes.io/basic-auth
stringData:
  username: {{ $inst.elasticsearch.user.login | quote }}
  password: {{ $inst.elasticsearch.user.password | quote }}
  roles: superuser
{{- end }}
{{- end }}