version: "3.6"

services:
  elasticsearch:
    container_name: arlas-exploration-stack-elasticsearch
    env_file:
      - /environment/default/arlas-exploration-stack-elasticsearch
      - /environment/user/arlas-exploration-stack-elasticsearch
    healthcheck:
      test: ( (( "$$(curl -o /dev/stderr -s -w "%{http_code}" localhost:9200)" == 200 )) && nc --send-only </dev/null -v localhost 9300) || exit 1
      start_period: 30s
    image: docker.elastic.co/elasticsearch/elasticsearch:$ARLAS_EXPLORATION_STACK_ELASTICSEARCH_VERSION
    ports:
      - $ARLAS_EXPLORATION_STACK_ELASTICSEARCH_HTTP_PORT:9200
      - $ARLAS_EXPLORATION_STACK_ELASTICSEARCH_TRANSPORT_PORT:9300
