apiVersion: v1
kind: ConfigMap
metadata:
  name: arlas-logo-configmap
binaryData:
  logo-only.png: |-
    {{ .Values.uis.logoImagePng60x60Base64 }}
  spinner.gif: |-
    {{ .Values.uis.spinnerGifBase64 }}
  no-view.png: |-
    {{ .Values.uis.noViewPngBase64 }}
  arlas-logo-inner-white-24.png: |-
    {{ .Values.uis.logoInnerPngBase64 }}
