apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "arlasWebUserInterface.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.uis.wui.serviceName }}
  name: {{ .Values.uis.wui.serviceName }}
spec:
  replicas: {{ int .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "arlasWebUserInterface.labels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.uis.wui.serviceName }}
  template:
    metadata:
      labels:
        {{- include "arlasWebUserInterface.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.uis.wui.serviceName }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.uis.podSecurityContext | nindent 8 }}
      {{- with .Values.uis.wui.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.uis.wui.extraInitContainers }}
        {{ .Values.uis.wui.extraInitContainers | toYaml | nindent 12 }}
        {{- end }}
        {{- if .Values.uis.wui.basemapUrl }}
        - name: download-file
          image: curlimages/curl:latest
          command: ["sh", "-c"]
          args:
            - '[ ! -f "/usr/share/nginx/html/assets/basemap/data/world.pmtiles" ] && (echo "Downloading basemap from ${BASEMAP_URL} ..." && curl -L -o /usr/share/nginx/html/assets/basemap/data/world.pmtiles  ${BASEMAP_URL} && ls -hl /usr/share/nginx/html/assets/basemap/data/world.pmtiles ) || echo "Basemap already exists, skipping download."'
          env:
            - name: BASEMAP_URL
              value: {{ .Values.uis.wui.basemapUrl | quote }}
          volumeMounts:
            - mountPath: "/usr/share/nginx/html/assets/basemap/data"
              name: basemap-volume
        {{- end }}

      containers:
        - name: {{ .Values.uis.wui.serviceName }}
          image: {{ .Values.uis.wui.image }}
          securityContext:
            {{- toYaml .Values.uis.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.uis.servicePort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              port: http
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ARLAS_AUTHENT_FORCE_CONNECT
              value: {{ .Values.authent.forceConnect | quote  }}
            - name: ARLAS_AUTHENT_REDIRECT_URI
              value: {{ .Values.protocol }}://{{ .Values.dnsDomain }}{{ .Values.uis.hub.urlPrefix }}/callback
            - name: ARLAS_AUTHENT_SILENT_REFRESH_REDIRECT_URI
              value: {{ .Values.protocol }}://{{ .Values.dnsDomain }}{{ .Values.uis.hub.urlPrefix }}/silent-refresh.html

            {{- include "arlasWebUserInterface.auth2Env" . | nindent 12 }}

            {{- include "arlasWebUserInterface.linksEnv" . | nindent 12 }}

            {{- include "arlasWebUserInterface.servicesEnv" . | nindent 12 }}

            {{- include "arlasWebUserInterface.actionsEnv" . | nindent 12 }}

            # ENDPOINT CONFIGURATION
            - name: ARLAS_WUI_BASE_HREF
              value: {{ .Values.uis.wui.urlPrefix }}

            # USER INTERFACE CONFIGURATION
            - name: ARLAS_WHITELISTED_URLS
              value: {{ .Values.uis.wui.whitelistedUrls | quote }}
            - name: ARLAS_STATIC_LINKS
              value: {{ .Values.links | quote }}
            - name: ARLAS_TAB_NAME
              value: {{ .Values.uis.wui.tabName | quote }}
            - name: ARLAS_GEOCODING_ENABLED
              value: {{ .Values.enableGeocoding | quote }}
            - name: ARLAS_GEOCODING_FIND_PLACE_ZOOM_TO
              value: {{ .Values.geocodingZoomTo | quote }}
            - name: RESULTLIST_ENABLE_EXPORT
              value: {{ .Values.resultListEnableExport | quote }}
            - name: RESULTLIST_EXPORT_SIZE
              value: {{ .Values.resultListExportSize | quote }}
            - name: ARLAS_HISTOGRAMS_MAX_BUCKETS
              value: {{ .Values.histogramsMaxBucket | quote }}
            - name: ARLAS_EXPORT_HISTOGRAMS_NB_BUCKETS
              value: {{ .Values.histogramsExportNbBuckets | quote }}
          {{- with .Values.uis.wui.extraEnv }}
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- range $configurationName, $configurationInfo := .Values.configuration }}
            - name: {{ (index $.Values.configuration $configurationName).environmentVariable }}
              value: file://{{ (index $.Values.configuration $configurationName).mountPath }}
          {{- end }}

          volumeMounts:
            {{- if .Values.uis.wui.basemapUrl }}
            - mountPath: "/usr/share/nginx/html/assets/basemap/data"
              name: basemap-volume
            {{- end }}            
            {{- if .Values.uis.wui.customi18nConfigMap }}
            - mountPath: "/usr/share/nginx/html/assets/i18n/custom"
              name: custom-i18n-volume
            {{- end }}            
            - mountPath: "/usr/share/nginx/html/assets/styles/custom-style.css"
              name: custom-style-volume
              subPath: custom-style.css

            - name: arlas-about-and-tour-configmap-volume
              mountPath: "/usr/share/nginx/html/assets/about/about_en.md"
              subPath: about_en.md
            - name: arlas-about-and-tour-configmap-volume
              mountPath: "/usr/share/nginx/html/assets/about/about_fr.md"
              subPath: about_fr.md
            - name: arlas-about-and-tour-configmap-volume
              mountPath: "/usr/share/nginx/html/assets/tour/tour_en.json"
              subPath: tour_en.json
            - name: arlas-about-and-tour-configmap-volume
              mountPath: "/usr/share/nginx/html/assets/tour/tour_fr.json"
              subPath: tour_fr.json

         {{- with .Values.uis.wui.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with .Values.uis.wui.extraContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        {{- if .Values.uis.wui.basemapUrl }}
        - name: basemap-volume
          persistentVolumeClaim:
            claimName: basemap-pvc
        {{- end }}
        {{- if .Values.uis.wui.customi18nConfigMap }}
        - name: custom-i18n-volume
          configMap:
            name: {{ .Values.uis.wui.customi18nConfigMap }}
        {{- end }}            
        - name: custom-style-volume
          configMap:
            name: arlas-custom-style
        - name: arlas-about-and-tour-configmap-volume
          configMap:
            name: {{ .Values.uis.wui.aboutAndTourConfigMapName }}

        {{- with .Values.uis.wui.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      # NODE SELECTION      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
