apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basemap-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.basemap.storageSize }}
  storageClassName: {{ .Values.defaultStorageClass }}
