apiVersion: v1
data:
  custom-style.css: |

    arlas-timeline .arlas-time--tools .shortcut-button,
    arlas-timeline .arlas-time--tools .arlas-date-picker-input-from,
    arlas-timeline .arlas-time--tools .arlas-date-picker-input-to {
      background-color: {{ .Values.uis.colors.arlas.bg  }};
    }


    /* Slider toggle */
    html .mat-mdc-slide-toggle.mat-accent {
      /* For the handle */
      --mdc-switch-selected-focus-state-layer-color: {{ .Values.uis.colors.handle.color }};
      --mdc-switch-selected-handle-color: {{ .Values.uis.colors.handle.color }}
      --mdc-switch-selected-hover-state-layer-color: {{ .Values.uis.colors.handle.color }}
      --mdc-switch-selected-pressed-state-layer-color: {{ .Values.uis.colors.handle.color }}
      --mdc-switch-selected-focus-handle-color: {{ .Values.uis.colors.handle.color }}
      --mdc-switch-selected-hover-handle-color: {{ .Values.uis.colors.handle.color }}
      --mdc-switch-selected-pressed-handle-color: {{ .Values.uis.colors.handle.color }}

      /* For the track */
      --mdc-switch-selected-focus-track-color: {{ .Values.uis.colors.arlas.bg }};
      --mdc-switch-selected-hover-track-color: {{ .Values.uis.colors.arlas.bg }};
      --mdc-switch-selected-pressed-track-color: {{ .Values.uis.colors.arlas.bg }};
      --mdc-switch-selected-track-color: {{ .Values.uis.colors.arlas.bg }};
    }

    /* Radio button */
    html .mat-mdc-radio-button.mat-accent {
      --mdc-radio-selected-focus-icon-color: {{ .Values.uis.colors.arlas.bg }};
      --mdc-radio-selected-hover-icon-color: {{ .Values.uis.colors.arlas.bg }};
      --mdc-radio-selected-icon-color: {{ .Values.uis.colors.arlas.bg }};
      --mdc-radio-selected-pressed-icon-color: {{ .Values.uis.colors.arlas.bg }};
      --mat-radio-checked-ripple-color: {{ .Values.uis.colors.arlas.bg }};
    }

    html {
      /* Input */
      --mdc-filled-text-field-caret-color: {{ .Values.uis.colors.arlas.bg }};
      --mdc-filled-text-field-focus-active-indicator-color: {{ .Values.uis.colors.arlas.bg }};
      --mdc-filled-text-field-focus-label-text-color: {{ .Values.uis.colors.arlas.bg }};
      --mat-option-selected-state-label-text-color: {{ .Values.uis.colors.arlas.bg }};
      --mat-select-focused-arrow-color: {{ .Values.uis.colors.arlas.bg }};

      /* Checkbox */
      --mdc-checkbox-selected-focus-icon-color: {{ .Values.uis.colors.arlas.bg }};
      --mdc-checkbox-selected-hover-icon-color: {{ .Values.uis.colors.arlas.bg }};
      --mdc-checkbox-selected-icon-color: {{ .Values.uis.colors.arlas.bg }};
      --mdc-checkbox-selected-pressed-icon-color: {{ .Values.uis.colors.arlas.bg }};
      --mdc-checkbox-selected-focus-state-layer-color: {{ .Values.uis.colors.arlas.bg }};
      --mdc-checkbox-selected-hover-state-layer-color: {{ .Values.uis.colors.arlas.bg }};
      --mdc-checkbox-selected-pressed-state-layer-color: {{ .Values.uis.colors.arlas.bg }};

      /* Datepicker & ARLAS components */
      --arlas-theme-color: {{ .Values.uis.colors.arlas.bg }};
    }

    /* Spinner */
    html .mat-accent {
      --mdc-circular-progress-active-indicator-color: {{ .Values.uis.colors.arlas.bg }};
    }

    /* ARLAS specific components */
    /* Map */
    .mapgl-settings__actions .mapgl-settings__actions--apply {
      --mdc-text-button-label-text-color: {{ .Values.uis.colors.arlas.bg }};
    }

    /* Layer download */
    arlas-admonition-card .admonition {
      border-color: {{ .Values.uis.colors.arlas.bg }} !important;
    }
    arlas-admonition-card .admonition-title {
      background-color: {{ .Values.uis.colors.arlas.bg }}4d !important;
    }

    html .dark-theme .resultitem__cell--label__filled {
      color: #b1c4d5 !important;
    }

    html .dark-theme {
      --mat-expansion-container-text-color: #b1c4d5;
      --mat-form-field-filled-input-text-color: #b1c4d5;
      --mat-expansion-header-text-color: #b1c4d5;
      --mat-sidenav-content-text-color: #b1c4d5;
      --mat-sys-primary: #2F6BFF;
      --mat-sys-on-primary: #b1c4d5;
      --mat-sys-inverse-primary: #2f5ab4;
      --mat-sys-secondary: #E33E6B;
      --mat-sys-on-secondary: #b1c4d5;
      --mat-sys-inverse-secondary: #96435c;
      --mat-sys-error: #f44336;
      --mat-sys-on-error: #b1c4d5;
      --mat-sys-inverse-error: #e53935;
      --mat-sys-shadow: #232426;
      --mat-sys-surface: #242f4c;
      --mat-sys-on-surface: #b1c4d5;
      --mat-sys-surface-variant: #1E293B;
      --mat-sys-on-surface-variant: #F1b1c4d5F5F9;
      --mat-sys-background: #192035;
      --mat-sys-inverse-surface: #b1c4d5;
      --mat-sys-inverse-on-surface: rgba(24, 22, 22, 0.87);
      --mat-sys-outline: rgba(255, 255, 255, .12);
      --mat-sys-outline-variant: #293F70;
      --mat-sys-error-container: #b71c1c;
      --mat-sys-on-background: #b1c4d5;
      --mat-sys-on-error-container: #b1c4d5;
      --mat-sys-on-primary-container: #b1c4d5;
      --mat-sys-on-primary-fixed: #b1c4d5;
      --mat-sys-on-primary-fixed-variant: #b1c4d5;
      --mat-sys-on-secondary-container: #b1c4d5;
      --mat-sys-on-secondary-fixed: #b1c4d5;
      --mat-sys-on-secondary-fixed-variant: #b1c4d5;
      --mat-sys-on-tertiary: #b1c4d5;
      --mat-sys-on-tertiary-container: #b1c4d5;
      --mat-sys-on-tertiary-fixed: #b1c4d5;
      --mat-sys-on-tertiary-fixed-variant: #b1c4d5;
      --mat-sys-primary-container: #001946;
      --mat-sys-primary-fixed: #2F6BFF;
      --mat-sys-primary-fixed-dim: #2F6BFF;
      --mat-sys-scrim: #232426;
      --mat-sys-secondary-container: #3f001a;
      --mat-sys-secondary-fixed: #E33E6B;
      --mat-sys-secondary-fixed-dim: #E33E6B;
      --mat-sys-surface-bright: #424242;
      --mat-sys-surface-container: #242f4c;
      --mat-sys-surface-container-high: #1E293B;
      --mat-sys-surface-container-highest: #424242;
      --mat-sys-surface-container-low: #242f4c;
      --mat-sys-surface-container-lowest: #424242;
      --mat-sys-surface-dim: #424242;
      --mat-sys-surface-tint: #424242;
      --mat-sys-tertiary: #E33E6B;
      --mat-sys-tertiary-container: #3f001a;
      --mat-sys-tertiary-fixed: #E33E6B;
      --mat-sys-tertiary-fixed-dim: #E33E6B;
    }

    html {
      --mat-sys-primary: #2196f3;
      --mat-sys-on-primary: white;
      --mat-sys-inverse-primary: #64b5f6;
      --mat-sys-secondary: #ff4081;
      --mat-sys-on-secondary: white;
      --mat-sys-inverse-secondary: #f06292;
      --mat-sys-error: #f44336;
      --mat-sys-on-error: white;
      --mat-sys-inverse-error: #e57373;
      --mat-sys-shadow: black;
      --mat-sys-surface: white;
      --mat-sys-on-surface: rgba(0, 0, 0, .87);
      --mat-sys-surface-variant: #f6f6f6;
      --mat-sys-on-surface-variant: rgba(0, 0, 0, .54);
      --mat-sys-background: #fafafa;
      --mat-sys-inverse-surface: #424242;
      --mat-sys-inverse-on-surface: white;
      --mat-sys-outline: rgba(0, 0, 0, .12);
      --mat-sys-outline-variant: rgba(0, 0, 0, .38);
      --mat-sys-error-container: #ffebee;
      --mat-sys-on-background: rgba(0, 0, 0, .87);
      --mat-sys-on-error-container: #d32f2f;
      --mat-sys-on-primary-container: #1976d2;
      --mat-sys-on-primary-fixed: white;
      --mat-sys-on-primary-fixed-variant: white;
      --mat-sys-on-secondary-container: #c2185b;
      --mat-sys-on-secondary-fixed: white;
      --mat-sys-on-secondary-fixed-variant: white;
      --mat-sys-on-tertiary: white;
      --mat-sys-on-tertiary-container: #c2185b;
      --mat-sys-on-tertiary-fixed: white;
      --mat-sys-on-tertiary-fixed-variant: white;
      --mat-sys-primary-container: #e3f2fd;
      --mat-sys-primary-fixed: #2196f3;
      --mat-sys-primary-fixed-dim: #2196f3;
      --mat-sys-scrim: black;
      --mat-sys-secondary-container: #fce4ec;
      --mat-sys-secondary-fixed: #ff4081;
      --mat-sys-secondary-fixed-dim: #ff4081;
      --mat-sys-surface-bright: white;
      --mat-sys-surface-container: white;
      --mat-sys-surface-container-high: white;
      --mat-sys-surface-container-highest: white;
      --mat-sys-surface-container-low: white;
      --mat-sys-surface-container-lowest: white;
      --mat-sys-surface-dim: white;
      --mat-sys-surface-tint: white;
      --mat-sys-tertiary: #ff4081;
      --mat-sys-tertiary-container: #fce4ec;
      --mat-sys-tertiary-fixed: #ff4081;
      --mat-sys-tertiary-fixed-dim: #ff4081;
    }




kind: ConfigMap
metadata:
  name: arlas-custom-style
