apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "arlasWebUserInterface.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.uis.builder.serviceName }}
  name: {{ .Values.uis.builder.serviceName }}
spec:
  replicas: {{ int .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "arlasWebUserInterface.labels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.uis.builder.serviceName }}
  template:
    metadata:
      labels:
        {{- include "arlasWebUserInterface.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.uis.builder.serviceName }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.uis.builder.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.uis.builder.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Values.uis.builder.serviceName }}
          image: {{ .Values.uis.builder.image }}
          ports:
            - name: http
              containerPort: {{ .Values.uis.servicePort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.uis.builder.urlPrefix }}
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.uis.builder.urlPrefix }}
              port: http
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if .Values.uis.builder.extraEnvVars }}
            {{ .Values.uis.builder.extraEnvVars | toYaml | nindent 12 }}
            {{- end }}

            {{- include "arlasWebUserInterface.auth2Env" . | nindent 12 }}

            {{- include "arlasWebUserInterface.linksEnv" . | nindent 12 }}

            {{- include "arlasWebUserInterface.servicesEnv" . | nindent 12 }}

            - name: ARLAS_AUTHENT_FORCE_CONNECT
              value: {{ .Values.authent.forceConnect | quote  }}
            - name: ARLAS_AUTHENT_REDIRECT_URI
              value: {{ .Values.protocol }}://{{ .Values.dnsDomain }}{{ .Values.uis.hub.urlPrefix }}/callback
            - name: ARLAS_AUTHENT_SILENT_REFRESH_REDIRECT_URI
              value: {{ .Values.protocol }}://{{ .Values.dnsDomain }}{{ .Values.uis.hub.urlPrefix }}/silent-refresh.html

            # BUILDER CONFIGURATION
            - name: ARLAS_BUILDER_BASE_HREF
              value: {{ .Values.uis.builder.urlPrefix | quote }}
            - name: ARLAS_BASEMAPS
              value: {{ .Values.uis.builder.basemaps | quote }}
            - name: ARLAS_EXTERNAL_NODE_PAGE
              value: {{ .Values.uis.builder.allowExternalNodeConfiguration | quote }}
            - name: ARLAS_ENABLE_ADVANCED_FEATURES
              value: {{ .Values.uis.builder.advancedFeatures | default "false" | quote }}

          {{- with .Values.uis.builder.extraEnv }}
            {{ toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            - name: arlas-builder-about-configmap-volume
              mountPath: "/usr/share/nginx/html/assets/about/about_en.md"
              subPath: about_en.md
            - name: arlas-builder-about-configmap-volume
              mountPath: "/usr/share/nginx/html/assets/about/about_fr.md"
              subPath: about_fr.md

          {{- with .Values.uis.builder.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}

      {{- with .Values.uis.builder.extraContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: arlas-builder-about-configmap-volume
          configMap:
            name: {{ .Values.uis.builder.aboutConfigMapName }}
      {{- with .Values.uis.builder.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}


      # NODE SELECTION      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}