{{- if eq .Values.uis.hub.aboutConfigMapName "arlas-hub-default-about-configmap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: arlas-hub-default-about-configmap
data:
  about_en.md: |-
    # ARLAS Hub, powered by Gisaïa<br>
    __ARLAS Hub__ is an opensource solution to manage __ARLAS Exploration__ dashboards, which are designed to explore and analyze Geo BigData.


    Visit http://arlas.io for more information or contact us at contact@gisaia.com.
    Report any issue to support@gisaia.com or on the [GitHub repository](https://github.com/gisaia/ARLAS-wui-hub).

    The ARLAS solution relies on:
    - Dropwizard
    - Maven
    - Elasticsearch
    - Angular
    - D3js
    - Node
    - NPM
    - Mapbox
    - Maplibre

    Powered by __Gisaïa__
  about_fr.md: |-
    # ARLAS Hub, powered by Gisaïa<br>
    __ARLAS Hub__ est une solution opensource de gestion des dashoards __ARLAS Exploration__ dashboards, qui sont destinés à l'exploration et à l'analyse Geo BigData.


    Visitez http://arlas.io pour plus d'informations et contactez nous par mail à l'adresse contact@gisaia.com.
    Vous pouvez rapporter tous problèmes à l'adresse support@gisaia.com ou sur le [répertoire GitHub](https://github.com/gisaia/ARLAS-wui-hub).

    La solution ARLAS est basée sur:
    - Dropwizard
    - Maven
    - Elasticsearch
    - Angular
    - D3js
    - Node
    - NPM
    - Mapbox
    - Maplibre

    Powered by __Gisaïa__
{{- end }}