apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "arlasWebUserInterface.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.uis.famWui.serviceName }}
  name: {{ .Values.uis.famWui.serviceName }}
spec:
  replicas: {{ int .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "arlasWebUserInterface.labels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.uis.famWui.serviceName }}
  template:
    metadata:
      labels:
        {{- include "arlasWebUserInterface.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.uis.famWui.serviceName }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.uis.famWui.serviceName }}
          image: {{ .Values.uis.famWui.image }}
          ports:
            - name: http
              containerPort: {{ .Values.uis.servicePort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.uis.famWui.urlPrefix }}
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.uis.famWui.urlPrefix }}
              port: http
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:

            {{- include "arlasWebUserInterface.auth2Env" . | nindent 12 }}

            {{- include "arlasWebUserInterface.linksEnv" . | nindent 12 }}

            {{- include "arlasWebUserInterface.servicesEnv" . | nindent 12 }}

            - name: ARLAS_AUTHENT_FORCE_CONNECT
              value: "true"
            - name: ARLAS_AUTHENT_REDIRECT_URI
              value: {{ .Values.protocol }}://{{ .Values.dnsDomain }}{{ .Values.uis.famWui.urlPrefix }}/callback
            - name: ARLAS_AUTHENT_SILENT_REFRESH_REDIRECT_URI
              value: {{ .Values.protocol }}://{{ .Values.dnsDomain }}{{ .Values.uis.famWui.urlPrefix }}/silent-refresh.html

            # USER INTERFACE CONFIGURATION
            - name: ARLAS_STATIC_LINKS
              value: {{ .Values.links | toPrettyJson | quote }}
            - name: ARLAS_TAB_NAME
              value: {{ .Values.uis.famWui.tabName | quote }}
            - name: FAM_DEFAULT_PATH
              value: {{ .Values.uis.famWui.famDefaultURL | quote }}
            - name: FAM_COLLECTION
              value: {{ .Values.uis.famWui.collectionName | quote }}
            - name: FAM_ARCHIVES_PAGES_SIZE
              value: {{ .Values.uis.famWui.archivePageSize | quote }}
            - name: FAM_FILES_PAGES_SIZE
              value: {{ .Values.uis.famWui.filePageSize | quote }}
            - name: APROC_CATALOG
              value: {{ .Values.uis.famWui.catalog | quote }}
            - name: AIRS_COLLECTION
              value: {{ .Values.uis.famWui.collectionName | quote }}



      # NODE SELECTION      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}