name: Test Kubernetes ARLAS Exploration stack
on: 
  push:
    paths:
      - 'k8s/**'
      - 'conf/aias/**'
      - .github/workflows/k8s_tests.yaml

jobs:
  aias-on-k8s-cluster:
    runs-on: runner-8core-32gb
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      - uses: actions/checkout@v4.1.4

      - name: Add bitnami repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Install yq
        run: sudo snap install yq

      - name: Configure dns naming
        run: ./k8s/scripts/configure_for_tests.sh 
        
      - name: deploy arlas
        run: ./k8s/scripts/start.sh 
        
      - name: wait arlas running
        run: ./k8s/scripts/wait_until_running.sh        
