name: Test Kubernetes ARLAS Exploration stack
on: 
  push:
    paths:
      - 'k8s/**'

jobs:
  aias-on-k8s-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      - uses: actions/checkout@v4.1.4

      - name: Add bitnami repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Update aias dependencies
        run: helm dependency update k8s/charts/aias

      - name: Build aias dependencies
        run: helm dependency build k8s/charts/aias

      - name: Install aias
        run: helm install aias k8s/charts/aias

      - name: Copy files
        run: ./k8s/scripts/copy_files.sh
