name: Test Kubernetes ARLAS Exploration stack

on: push

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      - uses: actions/checkout@v4.1.4
      - name: Build aias dependencies
        run: helm dependency build k8s/charts/aias
      - name: Install aias
        run: helm install aias k8s/charts/aias
